### ISSUE TITLE
chown operation not permitted

### ISSUE THREAD

**Issue by timmillwood** [bastienwirtz/homer#103]
```
chown: /www/assets/house-icon.png: Operation not permitted
chown: /www/assets/icons/android-chrome-maskable-512x512.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon-60x60.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon.png: Operation not permitted
chown: /www/assets/icons/safari-pinned-tab.svg: Operation not permitted
chown: /www/assets/icons/favicon-16x16.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon-152x152.png: Operation not permitted
chown: /www/assets/icons/msapplication-icon-144x144.png: Operation not permitted
chown: /www/assets/icons/android-chrome-maskable-192x192.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon-180x180.png: Operation not permitted
chown: /www/assets/icons/mstile-150x150.png: Operation not permitted
chown: /www/assets/icons/android-chrome-192x192.png: Operation not permitted
chown: /www/assets/icons/android-chrome-512x512.png: Operation not permitted
chown: /www/assets/icons/favicon-32x32.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon-76x76.png: Operation not permitted
chown: /www/assets/icons/apple-touch-icon-120x120.png: Operation not permitted
chown: /www/assets/icons: Operation not permitted
chown: /www/assets/icons: Operation not permitted
chown: /www/assets/manifest.json: Operation not permitted
chown: /www/assets/tools/grafana.png: Operation not permitted
chown: /www/assets/tools/sample.png: Operation not permitted
chown: /www/assets/tools/prometheus.png: Operation not permitted
chown: /www/assets/tools/sample2.png: Operation not permitted
chown: /www/assets/tools: Operation not permitted
chown: /www/assets/tools: Operation not permitted
/entrypoint.sh: exec: line 15: su-exec: not found
```

**Comment by AlexanderEDavis** [comment]
Run it as admin

**Comment by timmillwood** [comment]
I'm running in docker.

**Comment by AlexanderEDavis** [comment]
Is it a nginx docker? Are you able to access the directories while it is stopped? If so male the changes when the container is not running.

**Comment by GlennToms** [comment]
I think that the permissions for your mount doesn't match the user and group.  What does
`ls -la` output when you run it on your mounted volume path?

**Comment by Johannp02180** [comment]
I have the same problem, doing your command shows the same permissions as the other working docker containers. This happened to me suddenly with no changes and then suddenly I get all the same errors.

**Comment by GlennToms** [comment]
I need to see the output.  I can't help without it

**Comment by Johannp02180** [comment]
Yes, sorry. Here you go:

```
pi@raspberrypi:~/docker/homer $ ls -la
total 16
drwxr-xr-x  3 pi pi 4096 Jul  5 01:12 .
drwxr-xr-x 13 pi pi 4096 Jul  5 01:12 ..
drwxr-xr-x  3 pi pi 4096 Jul  5 01:12 assets
-rw-r--r--  1 pi pi 2645 Jul  5 01:12 config.yml
```

**Comment by GlennToms** [comment]
If you do `id pi` what number do you get 0 or 1000 or another number?
Fix will be to change your docker command user and group to match the same numbers.
`docker run -e "UID=1000" -e "GID=1000" [...]`

**Comment by Johannp02180** [comment]
I get

 `pi@raspberrypi:~/docker/homer $ id  pi
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),105(input),109(netdev),999(spi),998(i2c),997(gpio),995(docker)`

**Comment by GlennToms** [comment]
Add these environment variables to your docker command. 
`docker run -e "UID=1000" -e "GID=1000"`
Homer runs as user 911 but the folder on your pi is running as 1000.  The above command will fix it

**Comment by Johannp02180** [comment]
I use docker-compose and my config is

```
version: '2'
services:
    homer:
        ports:
            - 8095:8080
        volumes:
            - /home/pi/docker/homer/config.yml:/www/config.yml
            - /home/pi/docker/homer/assets/:/www/assets
        image: b4bz/homer:latest
        environment:
            - PUID=1000
            - PGID=1000
        restart: unless-stopped
```

**Comment by GlennToms** [comment]
No problem, you have an extra letter P
change 
`environment:
            - PUID=1000
            - PGID=1000`
To
`environment:
            - UID=1000
            - GID=1000`

**Comment by Johannp02180** [comment]
Hmmm, I just tried removing the P (I got the P from linuxserver configs) and I'm still getting the same operation not permitted errors.

Thanks in advance.

**Comment by GlennToms** [comment]
Hmm I'm not sure at the moment then.  I'd have to fire up my pi and check.  Give me a couple of hours to get that tested.

**Comment by Johannp02180** [comment]
No problem, thank you for the help so far.

**Comment by Borkuz** [comment]
I got sort off the same problem on my rapsberry pi. 
this is the command i run:
`docker run -e "UID=1000" -e "GID=1000" -p 8888:8080 -v /home/pi.config/appdate/homre:/www/assets b4bz/homer:latest`

and get this output:
`chown: /www/assets/*: No such file or directory
/entrypoint.sh: exec: line 15: su-exec: not found`

**Comment by sebrink** [comment]
Same issues as above.

Trying to use docker-compose to set this up:
```
root@odroid:~/homer# cat docker-compose.yml
---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /root/homer/assets/:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
```

I get this output:
```
root@odroid:~/homer# docker-compose up
Creating network "homer_default" with the default driver
Creating homer ... done
Attaching to homer
homer    | chown: /www/assets/*: No such file or directory
homer    | /entrypoint.sh: exec: line 15: su-exec: not found
```

**Comment by ikaruswill** [comment]
+1 I'm facing the same issue on 
```
b4bz/homer:latest
DIGEST:sha256:b732944f26bc1e3745cae11eccd641f582b8f899154af391a6545ab62c196d3c
```

However, I'm not on a Raspberry Pi, I'm on an arm64 device.

Likewise, I get the same log output and have been running homer just fine until recently.

```
...
chown: /www/assets/icons: Operation not permitted
/entrypoint.sh: exec: line 15: su-exec: not found
```

**Comment by GlennToms** [comment]
I checked this out this morning and there is a problem with the last two lines in the entry point script.  I'll do more troubleshooting asap

**Comment by GlennToms** [comment]
In the docker we switch user then run the entrypoint script, that user doesn't have permission to run chown and su-exec.

Can someone test by removing the USER line (line 38 I think ) in either ARM docker files then rebuild and test?
I'm not at my computer until the weekend to test myself.

**Comment by sebrink** [comment]
Removed the `USER ${USER}` on line 38 of this file: https://github.com/bastienwirtz/homer/blob/master/Dockerfile.arm32v7 (changed the name to Dockerfile). I'm running on an odroid which is running 32bit Arm.

Docker-compose attempt, still failing in the same way as before:
```
root@odroid:~/homer# docker-compose build && docker-compose up
homer uses an image, skipping
Creating network "homer_default" with the default driver
Creating homer ... done
Attaching to homer
homer    | chown: /www/assets/*: No such file or directory
homer    | /entrypoint.sh: exec: line 15: su-exec: not found
homer exited with code 127
homer exited with code 127
homer exited with code 127
```

Contents of the Dockerfile:
```
root@odroid:~/homer# cat Dockerfile
# build stage
FROM node:lts-alpine as build-stage

WORKDIR /app

COPY package*.json ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# Multi arch build support
FROM alpine as qemu

ARG QEMU_VERSION="v4.2.0-7"

RUN wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/qemu-arm-static && chmod +x qemu-arm-static

# production stage
FROM arm32v7/alpine:3.11

COPY --from=qemu qemu-arm-static /usr/bin/

ENV USER darkhttpd
ENV GROUP darkhttpd
ENV GID 911
ENV UID 911
ENV PORT 8080

RUN addgroup -S ${GROUP} -g ${GID} && adduser -D -S -u ${UID} ${USER} ${GROUP} && \
    apk add -U darkhttpd && \
    rm /usr/bin/qemu-arm-static

COPY --from=build-stage --chown=${USER}:${GROUP} /app/dist /www/
COPY --from=build-stage --chown=${USER}:${GROUP} /app/dist/assets /www/default-assets
COPY --chown=${USER}:${GROUP} entrypoint.sh /entrypoint.sh

EXPOSE ${PORT}
VOLUME /www/assets
ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
```

My compose file, just in case you believe it to be a compose error (which I doubt, however just trying to give as much info as possible:
```
root@odroid:~/homer# cat docker-compose.yml
---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /root/homer/assets/:/www/assets
    ports:
      - 80:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
```
