### ISSUE TITLE
SVG showing off center

### ISSUE THREAD

**Issue by kocsenc** [bastienwirtz/homer#117]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/2752396/89162546-19b6b080-d529-11ea-8d31-b4e6f319210a.png">

I got the SVG from: https://upload.wikimedia.org/wikipedia/en/1/15/Pi-hole_vector_logo.svg

`config.yml`: 

```
[...]
  - name: "ZBox"
    icon: "fab fa-ubuntu"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.svg"
        subtitle: ""
        tag: "container"
        url: "https://zbox.local/admin"
        target: "_blank"
[...]
```

Edit: I should mention I'm running Safari - `Version 13.1.2 (15609.3.5.1.3)`
