### ISSUE TITLE
highlight-secondary transparency wrong on center links bar

### ISSUE THREAD

**Issue by simonporte** [bastienwirtz/homer#141]
Hello,

When applying transparency to highlight-secondary color palette (rgba value), the transparency is more opaque on the links bar than on the sides or top bar with same color and transparency value applied.

Sample of config.yml for color palette :
```yaml
theme: default
colors:
  dark:
    highlight-primary: rgba(51, 103, 214, 0.8)
    highlight-secondary: rgba(51, 103, 214, 0.8)
    background-image: "../assets/bg/stripes.jpg"
```

Result :

![msedge_X8n0WyGxhA](https://user-images.githubusercontent.com/32496803/97113919-a5d21180-16ed-11eb-93c9-9c2546e677e2.png)

Could you make the transparency the same on the link bar or add a tertiary-color palette ?

Thanks.
