### ISSUE TITLE
Feature request: Use navbar links as search presets

### ISSUE THREAD

**Issue by jo-me** [bastienwirtz/homer#165]
Is it currently possible to create links to homer that preset the search?

It would be cool to use the navbar links like shortcuts to searches, e.g.  "office", "media server", "infrastructure".
Or searches for items with a specific tag.

If the app would read query params you could create navbar items with regular links,  e.g.   homer.domain.com/?search=xyz or homer.domain.com/?tag=apps

**Comment by bastienwirtz** [comment]
Hi @jo-me!

That's a good idea, I will look into it :+1:

**Comment by bastienwirtz** [comment]
@jo-me I just [pushed](https://github.com/bastienwirtz/homer/commit/31bd77c81d6b8343a9ea5b81656d5b7ac962d58b) the search by URL feature, let me know if that works for you!
You can use the `?search=my-app` url parameter, and the URL should be updated as soon as you modify or cancel the search.

Cheers.

**Comment by jo-me** [comment]
Hi @bastienwirtz 
thanks for realizing that idea!
I just tried it out and it works as expected.

Here is my config example:

![image](https://user-images.githubusercontent.com/10351272/102638983-a66cae80-4158-11eb-8425-7cb316900afa.png)

```
links:
  - name: "All"
    icon: "fas fa-home"
    url: "/"
  - name: "Smart Home"
    icon: "fas fa-brain"
    url: "?search=smart"
  - name: "Infrastructure"
    icon: "fas fa-network-wired"
```

The link bar is kind of messed up on mobile or with smaller screens in general. Do you have an issue about that already?
