### ISSUE TITLE
Where is the dotted line?

### ISSUE THREAD

**Issue by Gory19** [bastienwirtz/homer#170]
Hi, first of all, congratulations on your work, it's fantastic.
Today I updated the image but the "dotted line" disappeared.
https://imgur.com/w8MPddg
Can it be put back?

**Comment by bastienwirtz** [comment]
Hi @Gory19!

Thanks for the feedback! I'm glad you like it.
Yeah I went a bit more minimalist and removed the dotter line, but you can get it back using the custom css option:

- Add the following to your `config.yml` (if you don't already have a custom css)
```yml
stylesheet:
  - "assets/custom.css"
```

- then creates the `assets/custom.css` file, with the following content:

```css
@charset "UTF-8";

body #app .group-title {
  padding-bottom: 8px;
  border-bottom: 1px dashed;
}
```

That should do the trick! By the way you can customize pretty much anything in this custom CSS file. 
Enjoy!
