### ISSUE TITLE
(Internet) Search bar in message

### ISSUE THREAD

**Issue by jo-me** [bastienwirtz/homer#172]
Maybe it is of interest to someone: I played aroung with integrating a search bar and while I couldn't integrate Google it worked quite well for DuckDuckGo.
The main reason is so that on Android I don't need to switch apps after starting homer when I want to search for something. That way i can always return to the dashboard from a search in the homer PWA .

![image](https://user-images.githubusercontent.com/10351272/102640098-4414ad80-415a-11eb-8726-4d213d927cc1.png)

```
message:
  content: '<img src="assets/tools/duckduckgo.png" style="margin-right:20px;"><iframe src="https://duckduckgo.com/search.html?prefill=Search DuckDuckGo&focus=yes&kz=1&kac=1&kn=1&kp=-2&k1=-1" style="overflow:hidden;margin:0;padding:0;width:calc(100% - 100px);height:60px;" frameborder="0"></iframe>'

```

It would be even better if it was integrated in the header so that it does not waste as much space, but it was more a POC.

**Comment by luixal** [comment]
As there is already one search bar in the navbar, maybe it would be better to think about a way to use it for also search for content with different engines (right now it only searches between Homer items).

In case someone wants to do something like this, I enjoyed playing a little bit a custom css file so it looks like this (i removed the icon on purpose):

![image](https://user-images.githubusercontent.com/615268/104044607-d4846200-51dd-11eb-8815-224acd75ca4c.png)

For getting this, you need to create a new css file in `/assets` (mine is called `message-bar.css`) with this content:

```css
.message {
    margin-top: -1.2rem !important;
    width: 115.5rem !important;
    margin-left: -16.5rem !important;
}

.message-header {
    display: none !important;
}

.message-body {
    padding-bottom: 0rem !important;
}
```

and then configure the file in `config.yml` file like this (using your css filename):

```yml
stylesheet:
  - "assets/message-bar.css"
```

and the message you wan to show. In this example:

```yml
message:
  style: "is-dark"
  icon: "fa fa-grin"
  content: '<iframe src="https://duckduckgo.com/search.html?prefill=Search DuckDuckGo focus=yes&kz=1&kac=1&kn=1&kp=-2&k1=-1" style="overflow:hidden;margin:0;padding:0;width:calc(100% - 100px);height:60px;" frameborder="0"></iframe>'
```

Obviously, this is not better way to make this...
