### ISSUE TITLE
Wrong Favicon of linked services on safari

### ISSUE THREAD

**Issue by Darathor17** [bastienwirtz/homer#188]
Hello,

first of all: congrats for this awesome app!

I'm running Homer via docker on an ubuntu machine.

When accessing via Safari, the favicon on any services I clicked remains homer's, see attached image:

<img width="763" alt="Screenshot 2021-02-01 at 21 40 30" src="https://user-images.githubusercontent.com/24258247/106517404-b954fb80-64d8-11eb-9694-0df9b2129d16.png">

For information it works correctly on Google Chrome and I have tried to empty safari Favicon caches to no avail.

My config.yaml is as follow:
```
---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home dashboard"
subtitle: "XXXXX"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: 4
connectivityCheck: true
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "XXXXX"
    icon: "fab fa-gitlab"
    url: "XXXXXX"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
### MEDIAS ###
  - name: "Medias"
    icon: "fas fa-film"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Plex Media Server"
        tag: "medias"
        url: "http://XXXXX:32400"
        target: "_blank" # optional html a tag target attribute
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "The Free Software Media System"
        tag: "medias"
        url: "http://XXXXX:8096"
        target: "_blank" # optional html a tag target attribute
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        subtitle: "BitTorrent Client over OpenVPN"
        tag: "medias"
        url: "http://XXXXX:9091"
        target: "_blank" # optional html a tag target attribute
```

Thx for any help!
