### ISSUE TITLE
Use logo in groups

### ISSUE THREAD

**Issue by Hanoko** [bastienwirtz/homer#195]
I would want to use an image for my groups, I have changed the icon parameter and configured the logo with a correct path to an image. Am I doing something wrong, or this isnt' possible?

Thanks in advance.

**Comment by netstx** [comment]
Take a look at this configuration example snippet from the [documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md):

```
# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Application"
    icon: "fas fa-code-branch"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
```

Doesn't look like it's possible at the moment.
