### ISSUE TITLE
[FEATURE] Service Tags as list instead of string

### ISSUE THREAD

**Issue by BashBeesAndBeeer** [bastienwirtz/homer#20]
## I'm submitting a ...
- [x] feature request

## Current Behavior

Current Example/Usage as displayed by `README.md`

```yml
services:
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        subtitle: "Continuous integration server"
        tag: "CI"
```

Only one tag is available to use

## Expected Behavior & Possible Solution

Multiple tags are available to search

```yml
services:
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        subtitle: "Continuous integration server"
        tag: 
          - "CI"
          - "continuous integration"
          - "pipeline"
```

One can use multiple tags. When searching, one does not necessarily need to remember the name of the service to find it in the dashboard.

## Context
The only instance I've seen the `tag` used in the web dashboard for searching. Changing the tag functionality to a list would make searching larger dashboards more useful.
