### ISSUE TITLE
[fr] specify default layout, list or column, in config file

### ISSUE THREAD

**Issue by Bobba-star** [bastienwirtz/homer#200]
I have many applications on my homepage, and I find using the table list view to be better.
Would be great to be able to specify the default layout for the page using the config.yml file.

**Comment by fbartels** [comment]
Similar to https://github.com/bastienwirtz/homer/pull/147

**Comment by bastienwirtz** [comment]
Hey there, 

Default layout option is available from the config file:
```yml
# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'
```

Note that once you used the navbar button to change the layout, your browser keeps it in memory and the default setting does not apply.
