### ISSUE TITLE
Automatic (scheduled) refresh of Homer Dashboard - refeshInterval

### ISSUE THREAD

**Issue by nodecentral** [bastienwirtz/homer#212]
I saw it mentioned in this issue ( https://github.com/bastienwirtz/homer/issues/210 ) that there’s a `refeshInterval` related to messages ..

However I can’t seem to see that option myself in my yaml, I always have to refresh the browser manually ? Where should that go ?

Also, if I don’t want to use messages, can I use the `refeshInterval`on its own so I can refresh elements like my pi-hole stats ?

**Comment by bastienwirtz** [comment]
Hi @nodecentral, 

`refeshInterval` is only related to the message system. Usage is described in the [sample config](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md#configuration) :
```yml
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  style: "is-warning"
  title: "Optional message!"
  icon: "fa fa-exclamation-triangle"
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
```

`refeshInterval` is not compatible with services like pi-hole for the moment.

Let me know is you have other questions.
