### ISSUE TITLE
bug: background-image: "" setting in config.yml using different path

### ISSUE THREAD

**Issue by yojoshb** [bastienwirtz/homer#220]
EDIT: Oops  just saw that this was brought up before in a closed issue regarding the background-image setting. My bad for not reading thoroughly, feel free to delete this or leave it up for visibility.

Hi, I just started using Homer and loving it so far! I'm not sure if it's intended or not but the `background-image:` theme setting may be looking into the wrong path; or I just misunderstood where to put the files. Icons and logos display correctly when in `/www/assets`

It seems to be looking for files in `/www/css/` rather than `/www/assets/` inside the running container. After setting a image path `background-image: "assets/wallpaper.png"` and refreshing the page my background-image was not being displayed so I inspected the page and found that it was failing to find the image and was looking for the file in `/css`. 

> GET http://MY-IP:PORT/css/assets/wallpaper.jpg 404 (Not Found)

After moving the wallpaper file to `/www/css/` inside of the container and setting `background-image: "wallpaper.png"` the image was being displayed properly. Not a big deal just a little confusing. For now I'll just mount /www/css to my host for background images. Here's my compose file for reference.

```
---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /docker/homer/:/www/assets
    ports:
      - 8080:8080
    restart: unless-stopped

```
