### ISSUE TITLE
Error: : [object ReadableStream]

### ISSUE THREAD

**Issue by damomato** [bastienwirtz/homer#230]
Hi, this error is popping up. I installed using Docker on DSM 6.2.4 and haven't made any changes to the config file.

Docker-compose
```
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      - PUID=1026
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - ./homer:/www/assets
    ports:
      - 8484:8080
    restart: unless-stopped
```

![image](https://user-images.githubusercontent.com/85538685/121284427-69b39000-c90f-11eb-810f-cf2780bbb87d.png)

Anyone have any suggestions to fix?

Thanks
