### ISSUE TITLE
Documentation for ping service is wrong

### ISSUE THREAD

**Issue by xconverge** [bastienwirtz/homer#249]
https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#ping

I just went to check to see what the ping service was all about and theres a copy paste error here. I would open a PR but I dont know what to put there instead, oops!

**Comment by ThomasDeNoobNL** [comment]
Hey @stubbfel, any chance you could help a bit here? Some people, including myself, have a lot of trouble with figuring out how to use your ping service. Thanks for making it btw, it has been on my wishlist for quite a while!

**Comment by stubbfel** [comment]
@ThomasDeNoobNL  sure , i hope i can help. 
Add `type = "Ping"` to the service item inside the config yml file, like: 
```yml
items:
   - name: "Awesome app"
     type: Ping
     logo: "assets/tools/sample.png"
     subtitle: "Bookmark example" tag: "app" 
     url: "https://www.reddit.com/r/selfhosted/" 
```
The thr ping service is enable. 
Be aware of the CORS issue, whe you try to ping a url which has another domain name as domain name of your homer service (see 
https://github.com/bastienwirtz/homer/pull/240#issuecomment-880156674 ).

In that case may pr #255 can help you.
