### ISSUE TITLE
New Sonarr service CORS error

### ISSUE THREAD

**Issue by beastboxio** [bastienwirtz/homer#250]
The Sonarr service isn't working for me and gives the below error in browser (MS Edge). 

`Access to fetch at 'http://192.168.1.2:8002/api/queue' from origin 'http://192.168.1.2:8001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

Error in UI:
`Connection error to Sonarr API, check url and apikey in config.yml`

I'm running Homer and Sonarr in docker containers, locally on port 8001 and 8002 respectively. I am running another app Overseerr, the same setup in a container on another local port, and that does interact with the Sonarr API without issue. These are running on a Synology DS918+ NAS if that makes a difference. No reverse proxy for these services.

My config.yml entry is as follows:

```
- name: "Sonarr"
  logo: "assets/tools/sonarr.svg"
  subtitle: "TV Collector"
  url: "http://192.168.1.2:8002"
  type: "Sonarr"
  apikey: "<MyAPIKey>"
```

docker-compose entries:
```
homer:
        image: b4bz/homer
        container_name: homer
        environment:
            - UID=${PUID}
            - GID=${PGID}
        volumes:
            - ${PATH_CONFIG}/homer:/www/assets
        ports:
            - 8001:8080
        restart: unless-stopped

sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${PATH_CONFIG}/sonarr:/config
            - ${PATH_MEDIA}:/media
        ports:
            - 8002:8989
        restart: unless-stopped
```
