### ISSUE TITLE
Category List Mode / Exception

### ISSUE THREAD

**Issue by flyingfishflash** [bastienwirtz/homer#252]
Having the following configuration results in an exception being thrown in the Javascript.

The exception is only triggered in 'Category List Mode' where the service names are in a vertical list and the items flow from left to right. (Not the default column grouping).

There also must be two pages.

The exception is triggered when you return to the '#' route from the second ('additional-page').

Using the latest docker image.

Configuration:

config.yml
```
---

title: "Local Services"
subtitle: "Subtitle"

header: true
footer: false


theme: default
colors:
  light:
    highlight-primary: "#ffffff"
    highlight-secondary: "#ffffff"
    highlight-hover: "#fafafa"
    background: "#ffffff"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#303030"
    #text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#90AFC5"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

links:
  - name: "Remote Services"
    url: "#additional-page"

services:
  - name: "Infrastructure"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Administration"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Monitoring"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Database"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Media"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Software Development"
    items:
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Local Service 1"
        url: 'https://www.example.com'
        target: "_blank"
```

additional-page.yml

```
---

title: "Remote Services"

links:
  - name: "Local Services"
    url: "#"

services:
  - name: "Weather"
    items:
      - name: "Remote Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 2"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 3"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 4"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 5"
        url: 'https://www.example.com'
        target: "_blank"
  - name: "Finance"
    items:
      - name: "Remote Service 1"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 2"
        url: 'https://www.example.com'
        target: "_blank"
      - name: "Remote Service 3"
        url: 'https://www.example.com'
        target: "_blank"

```   

Exception:

```
TypeError: t is undefined
    VueJS 26
    e App.vue:186
    l runtime.js:63
    S runtime.js:293
    A runtime.js:118
    Babel 6
    t App.vue:168
    e App.vue:165
    l runtime.js:63
    S runtime.js:293
    A runtime.js:118
    Babel 4
    t App.vue:163
    VueJS 15
    56d7 main.js:19
    Webpack 6
```
