### ISSUE TITLE
[API] Message with multiple objects in json

### ISSUE THREAD

**Issue by MoryCorp** [bastienwirtz/homer#257]
Hey,

I'm trying to display the result of this request in my dashboard : 

https://api.coingecko.com/api/v3/simple/price?ids=leash%2Cshiba-inu%2Cbone-shibaswap&vs_currencies=usd

Example : 

```
{"shiba-inu":{"usd":7.83e-06},"bone-shibaswap":{"usd":2.22},"leash":{"usd":1182.84}}
```

This is the code I am using in the config : 

```
  url: https://api.coingecko.com/api/v3/simple/price?ids=leash%2Cshiba-inu%2Cbone-shibaswap&vs_currencies=usd
  refreshInterval: 10000
  style: "is-dark"
  title: "Current Prices"
  icon: "fa fa-exclamation-triangle"
  mapping:
    content: ???
```

So is there a way to display the 3 objects ?
I am only able to select on in the content by using the name (leash) for example

Cheers !
