### ISSUE TITLE
Update docker image to be able to run as non-root user

### ISSUE THREAD

**Issue by justsomebody42** [bastienwirtz/homer#261]
Hi,

I'm running 21.07.1 in a Kubernetes cluster.
It works super smooth and I'm very happy with the application itself.

I would like to run the image as non-root user.
Are there plans to improve the security of the docker image?

My current Deployment looks like this and I'd be happy, if I could turn on runAsNonRoot and enable runAsUser instead of relying on the endpoint script to finally run the server with the provided userid :)

While I can understand that it is more end user friendly to repair file permissions and ownership during the startup, I think focussing on security and reminding users to prepare their environment accordingly would be beneficial during runtime.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      #      securityContext:
      #        runAsNonRoot: true
      volumes:
        - name: homer
          persistentVolumeClaim:
            claimName: homer
      containers:
        - name: homer
          image: b4bz/homer:21.07.1
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          #            runAsUser: 1032
          #            runAsGroup: 65537
          env:
            - name: UID
              value: "1032"
            - name: GID
              value: "65537"
          volumeMounts:
            - name: homer
              mountPath: /www/assets
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

```
