### ISSUE TITLE
Message not reading child object in JSON

### ISSUE THREAD

**Issue by fitur** [bastienwirtz/homer#286]
Im trying to utilize the message function but I can't seem to get it right:
```
message:
  url: https://my.domain.com/tautulli/api/v2?apikey=APIKEY&cmd=arnold
  mapping:
    content: response
  title: "Tautulli"
  content: "Couldn't get dynamic data from Tautulli."
```
Which shows the message content as: { "result": "success", "message": null, "data": "Dillon, you son of a bitch!" } in the dashboard, which is part of {"response": {"result": "success", "message": null, "data": "Dillon, you son of a bitch!"}} which comes from the Tautulli API.

When I try to map 'content' to the 'message' child object of the JSON response, the message returns the default content value "Couldn't get dynamic data from Tautulli.".

Am I doing something wrong?

<img width="699" alt="image" src="https://user-images.githubusercontent.com/10331814/133600319-93730a9d-4265-4992-b915-9f5f6d9603f8.png">
<img width="327" alt="image" src="https://user-images.githubusercontent.com/10331814/133600361-488de177-d280-40ed-9951-4e5f58dba6e3.png">
