### ISSUE TITLE
Log keep spam 127.0.0.1 "GET /" 200 2996 "" "Wget"

### ISSUE THREAD

**Issue by propserer** [bastienwirtz/homer#303]
My homer docker container log keep spamming with  
`1633369746 127.0.0.1 "GET /" 200 2996 "" "Wget" `

here my compose file look like

```
version: "2"
services:

homer:
        ports:
            - "7000:8080"
        environment:
            - UID=${PUID}
            - GID=${PGID}
        volumes:
            - ${AppData}/homer:/www/assets
        restart: unless-stopped
        image: b4bz/homer:latest
        container_name: homer
```

Test with raspberry pi and on my linux mint machine both spamming the log with the same 127.0.0.1 "GET /" 200 2996 "" "Wget"
when i check glances and ctop it cause cpu spike

**Comment by sargonas** [comment]
same, I was wondering about this as well as I notice it on my docker container as well, when I glanced at my Greylog server and saw it full of them.

**Comment by fbartels** [comment]
Its not the connectivity check from homer itself, but the container healthcheck that is the source of these. See https://github.com/bastienwirtz/homer/blob/451b1ac62450fb2c4f8e2382bcf422bb7a434700/Dockerfile#L28-L29

**Comment by sargonas** [comment]
Ahhhh that makes sense, thanks!

**Comment by fbartels** [comment]
Yes, a 5 second interval for the health check seems quite excessive.

**Comment by propserer** [comment]
How can i disable it?

**Comment by propserer** [comment]
> Ahhhh that makes sense, thanks! Knowing that I might just over-ride the intervals i the compose file, or maybe just disabled it entirely... I have other monitoring services in place anyways.

How can i disable the health check?

**Comment by sargonas** [comment]
You can override the health check parameters defined inside the container by simply adding them to your startup command or compose file. For the compose file, you  have 4 options you can set:

```
healthcheck:
  test: [actual test commands go here]
  interval: 1m1s
  timeout: 1s
  retries: 1
  start_period: 2s
  disable: true
```
  
  In the case of this image, I just added the following to kill it entirely for now until I take time to rethink how I want it to run long term:

```
healthcheck:
  disable: true
```
