### ISSUE TITLE
homer refuses the connection

### ISSUE THREAD

**Issue by maeries** [bastienwirtz/homer#320]
Suddenly my homer instance went down for no apparent reason and I can't get it online anymore. Caddy shows

```caddy    | {"level":"error","ts":1634991122.6001492,"logger":"http.log.error","msg":"dial tcp 172.18.0.10:8080: connect: connection refused","request":{"remote_addr":"217.84.45.61:63602","proto":"HTTP/2.0","method":"GET","host":"start.domain.com","uri":"/service-worker.js","headers":{"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"],"Accept-Language":["de,en-US;q=0.7,en;q=0.3"],"Accept-Encoding":["gzip, deflate, br"],"Service-Worker":["script"],"Sec-Fetch-Site":["same-origin"],"Te":["trailers"],"Accept":["*/*"],"Sec-Fetch-Dest":["serviceworker"],"Sec-Fetch-Mode":["same-origin"],"Cache-Control":["max-age=0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","proto_mutual":true,"server_name":"start.domain.com"}},"duration":0.001007384,"status":502,"err_id":"s81m7guya","err_trace":"reverseproxy.statusError (reverseproxy.go:858)"}```

every time I want to access homer. And when I try to reach it without any reverse proxy in between it doesn't work either (meaning I don't even get an entry in the homer logs)

Here's my docker-compose.yml:
```
version: '2'
services:
    homer:
        image: 'b4bz/homer:latest'
        restart: unless-stopped
        ports:
            - '8180:8080'
        volumes:
            - './assets/:/www/assets'
        networks:
            - caddy_net
            - default

networks:
  caddy_net:
    external: true
```

I, however, can ping homer using `/docker/caddy$ docker-compose exec caddy ping homer`

Edit:
A little bit backstory: I had this issue a couple of times in the past, like every couple of month, and was able to fix it by restarting the docker container or so. Today, after restarting it again a few times, it worked again, but after restarting it one more time, it now seems to stay broken.
