### ISSUE TITLE
Change height of Services line?

### ISSUE THREAD

**Issue by Sailing74** [bastienwirtz/homer#378]
I've added a custom logo (not icon) in front of services, and it turns out that the logo is being shown too large to fit into the entire row.

Is there some way I can change either line height or icon height?

![grafik](https://user-images.githubusercontent.com/5119859/154236457-6951b16b-3126-4785-a5b7-33be19ca1e27.png)

```
services:
  - name: "Server"
    # icon: "fas fa-cloud"
    logo: "assets/icons/logo.png"
    items:
```
