### ISSUE TITLE
icons not working

### ISSUE THREAD

**Issue by FlyingPersian** [bastienwirtz/homer#382]
Hello,

I'm running homer on my Raspberry Pi and 99% of it works fine. I'm trying a few icons both in the navbar and services, and some of them don't work for whatever reason:

faX fa-house
faX fa-photo-film
faX fa-key-skeleton-left-right

replace X with s, b, t, l etc.

When I use working ones instead (i.e. fas fa-cloud) it works fine. I tried multiple browsers, private mode, different machines, always the same result. I can obviously use similar icons, but I found those the most suitable. I tried others too, of course, and some work and others don't. 

Here the code for a non-working one:

Nav bar:

```
links:
  - name: "Home Assistant"
    icon: "fas fa-house"
    url: "xxx"
    target: "_blank" # optional html a tag target attribute
```

Services:

```
services:
  - name: "Stuff"
    icon: "fas fa-shuffle"
    items:
```

Here the code for a working one:

Nav bar:

```
links:
  - name: "Nextcloud"
    icon: "fas fa-cloud"
    url: "xxx"
    target: "_blank" # optional html a tag target attribute

```

Services:
```
services:
  - name: "Self-Hosting"
    icon: "fab fa-raspberry-pi"
    items:
```

The color settings etc. are all set to default. Changing between dark/light mode doesn't fix this. I'm not using any addon that interferes with this (Super Dark Mode Chrome extension is disable on this site). It happens on addon-less browsers as well anyway.

What might be the reason? I'm hoping that others can replicate the issue.
