### ISSUE TITLE
Improve docs with better CORS handling

### ISSUE THREAD

**Issue by Roundaround** [bastienwirtz/homer#396]
We get a lot of issues reported and questions in the Gitter chat about errors relating to CORS. We should mention the potential issue with CORS more prominently in the docs (i.e. early on in the custom services intro) and provide people with a better solution. The recommended proxy servers haven't been touched in years and I personally could not get them to work. Writing one is not super complicated so maybe it's time we provide an official solution. The one I use in my personal deployment looks like this:

```
import express, { json } from 'express';
import cors from 'cors';
import axios from 'axios';

const app = express();

app.use(json());
app.use(cors());

app.get('*', async (req, res, next) => {
  try {
    let target = req.originalUrl;
    if (target.startsWith('/')) {
      target = target.substring(1);
    }

    console.log(`Proxying request meant for '${target}'`);
    const response = await axios.get(target, {headers: req.headers});
    return res.json(response.data)
  } catch (err) {
    return res.status(500).send(err);
  }
});

console.log('App listening on port 3333');
app.listen(3333);
```

**Comment by espilioto** [comment]
For folks behind Traefik this is my config:

We define a middleware called cors-headers in config.yml:
```
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowOriginList:
          - https://homer.url.here
        accessControlAllowHeaders: ["x-api-key, Origin, Authorization"]
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
```

The middleware can then be assigned to routers with something like this in your docker-compose in each image:
`"traefik.http.routers.myservice.middlewares=cors-headers@file"`
DON'T FORGET THE SECURE ROUTER!!
`"traefik.http.routers.myservice-secure.middlewares=cors-headers@file"`

To verify it works you can inspect it from the dashboard:
![image](https://user-images.githubusercontent.com/8510006/162493564-db0aebd6-cccb-4fc8-a1ca-95cc0194650d.png)

**Comment by HeyItsJono** [comment]
For anyone looking for something easily deployable in the meantime whilst awaiting a solution, as a shameless self-plug you could try [PyCors](https://hub.docker.com/r/heyitsjono/pycors).

**Comment by KibosJ** [comment]
If using SWAG I got mine working by creating a cors.conf in the nginx folder

```
set $cors '';
if ($http_origin ~ '^https?://(localhost|homer.domain\.com)') {
        set $cors 'true';
}

if ($cors = 'true') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET,OPTIONS,PUT' always;
        add_header 'Access-Control-Allow-Headers' 'x-api-key,Origin,Authorization' always;
        add_header 'Access-Control-Expose-Headers' 'Authorization' always;
}
```

Then adding this to each server conf (Portainer, Sonarr, etc.)

```
proxy_hide_header 'Access-Control-Allow-Origin';
include /config/nginx/cors.conf;
```

Sonarr's api block in SWAG would become:

```
location ~ (/sonarr)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app sonarr;
        set $upstream_port 8989;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_hide_header 'Access-Control-Allow-Origin';
        include /config/nginx/cors.conf;
   }
```

**Comment by wardwygaerts** [comment]
I have it working in Traefik. But I also use `forwardAuth` (Google authentication) and when I enable this middleware together with the one for cors, it's not working anymore:
```
Access to fetch at 'https://accounts.google.com/o/oauth2/auth?client_id=xxxxxx.apps.googleusercontent.com&prompt=select_account&redirect_uri=https%3A%2F%2Foauth.domain.com%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=xxxxxf%3Agoogle%3Ahttps%3A%2F%2Fportainer.domain.com%2Fapi%2Fendpoints' (redirected from 'https://portainer.domain.com/api/endpoints') from origin 'https://portal.domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by espilioto** [comment]
Hmmm, examine the response with and without it, maybe you must allow a specific header through.

**Comment by wardwygaerts** [comment]
How can I find out missing headers? I always check via Dev Tools and then Console.

**Comment by espilioto** [comment]
Sure, that's how I'd go about it too.
If for some reason something feels funky, just try doing the same thing without the proxy; I usually just start the same image in a different docker network to make sure everything works as it should without it and then examine the headers.

**Comment by wardwygaerts** [comment]
I thought I solved it in the past (everything is working for Sonarr, Radarr & Prowlarr.
But I keep getting the cors messages for Portainer, Uptime-Kuma and Paperless.

`Access to fetch at 'https://portainer.*******.com/api/endpoints' from origin 'https://homer.**********.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

![image](https://user-images.githubusercontent.com/7568498/190715438-8661c622-f64e-4677-b1b3-1d8f93800d57.png)

I used this middleware in Traefik v2.4 (a '*' for accessControlAllowOriginList for testing):
```
cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowOriginList: "*"
        accessControlAllowHeaders: ["X-Api-Key,Origin,Authorization,X-Requested-With,Content-Type,Accept,Access-Control-Request-Method"]
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
```
