### ISSUE TITLE
Docker image doesn't work on raspberry pi

### ISSUE THREAD

**Issue by kushpvo** [bastienwirtz/homer#40]
when i run docker container, it automatically exits. log shows this:
`standard_init_linux.go:211: exec user process caused "exec format error"`

I guess the dockerfile is not build for raspberry pi?

**Comment by Tobix99** [comment]
Yes you are right, there isn't an ARM Build, but I've build it by my own. Here is the Dockerfile I used:

```FROM alpine:3.11

ENV USER darkhttpd
ENV GROUP darkhttpd
ENV GID 911
ENV UID 911

RUN addgroup -S ${GROUP} -g ${GID} && adduser -D -S -u ${UID} ${USER} ${GROUP} && apk add --no-cache -U darkhttpd git && git clone https://github.com/bastienwirtz/homer /www/

USER darkhttpd

ENTRYPOINT ["darkhttpd","/www/"]
```

But remember to build it on the RPi or else it's still not an ARM Image.

**Comment by kushpvo** [comment]
@Tobix99 Thanks for the info, sorry, i am kind of a noob here. So, how should i use the docker file you mentioned?
Git clone this repo and replace the repo's dockerfile with this file? And then do what? 
Also, after doing that, do i need to do docker-compose or docker create? 
I'm sorry if i'm asking a lot but I have zero knowledge of docker xD

**Comment by Tobix99** [comment]
No problem! So I've a setup with Docker-compose, where I put everything in my compose file and then replace image with `build: "homer/"` and then place a folder in the same folder as the docker-compose.yml and in this homer folder I place the Dockerfile. After that only do docker-compose up -d and it should be running. 

Here is an excerpt of my compose file:

docker-compose.yml
```
version: "2"
services:
  homer:
    container_name: "Homer"
    build: homer/
    ports:
      - 4481:8080 
    volumes:
      - '/home/theinze/dockerdata/homer/config/config.yml:/www/config.yml'
      - '/home/theinze/dockerdata/homer/assets/:/www/assets'
    restart: unless-stopped
```
