### ISSUE TITLE
Permissions/Volume problems running homer in docker-swarm - homer 'bricks' NFS volume

### ISSUE THREAD

**Issue by Lorthiz** [bastienwirtz/homer#408]
I have pretty standard RPI 4 cluster - 1 manager, 3 nodes. In addition to that there is OpenMediaVault running on additional machine.
Services run on cluster use NFS volumes(exposed by OpenMediaVault) to get configuration from and store runtime data there.

```
version: '3.2'
services:
  dashboard:
    image: b4bz/homer:latest
    volumes:
      - type: volume
        source: dashboard-volume
        target: /www/assets
        volume:
          nocopy: true
    environment:
      - USER=root
      - GROUP=root
      - UID=1000
      - GID=1000
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard.rule=Host(`example.com`)
        - traefik.http.services.dashboard.loadbalancer.server.port=8080
        - traefik.docker.network=example_default
        - traefik.http.routers.dashboard.tls.domains[0].main=example.com
        - traefik.http.routers.dashboard.tls.domains[0].sans=*.example.com
        - traefik.http.routers.dashboard.tls=true
        - traefik.http.routers.dashboard.tls.certresolver=production

  dashboard-volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.50.200,nolock,soft,rw
      device: ":/export/storage/dashboard"
```

Running this config with empty 'dashboard' folder in my NFS will create all homer specific files in that location and 'brick' it from futher modifications on my Windows machine. Trying to change 'config.yml' while container is running will result in getting a mesage that 'File is already being used by another process' and more to that after removing service from the stack and purging node - due to some stragne behaviour I am able to modify some files but trying to remove whole folder still 'restores files inside 'icons' and 'tools' folders. So now I am stuck with folder I can't remove on my NFS... 
It's the first time I encountered those problems using NFS volumes, other applications(eg, traefik,  mariadb, docker registry to name few) do not have a problem with that.
I know a lot of people ara having issues with permissions running in clusters, but I did not expected this :D
Did you had similar issues? Or do you know how meaby it can be fixed?
