### ISSUE TITLE
Token substitution

### ISSUE THREAD

**Issue by JonSilver** [bastienwirtz/homer#412]
It would be great to be able to include tokens such as %BASE_URL% in fields in the yaml, to be substituted at runtime with the contents of a matching environment variable.

Happy to contribute a PR if wanted.

Thanks,
Jon

**Comment by fbartels** [comment]
For the base url this does not really seem necessary for me. You can just work with relative urls and the browser will take care of the request going to domain1.com/path or domain2.com/path based on the url you’re accessing Homer from.

**Comment by Roundaround** [comment]
I like the idea of this - I'd have to think a bit on what tokens would be useful though. I agree that BASE_URL is more or less useless but we surely come up with something

**Comment by matthewstrasiotto** [comment]
A lot of apps tend to be hosted on separate sub-domain, eg: `homer.example.com`, `app2.example.com` , so yeah, base_url would be appropriate, eg

```yml
services:
  - name: "Application"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Bookmark example"
        tag: "app"
        # Root_tld
        url: "blog.${root_tld}"
        target: "_blank" # optional html tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "auth.${root_tld}"
```

Personally I literally run my homer configs through a templating program that looks like this:

```bash
#!/usr/bin/env bash

repo_root="$(git rev-parse --show-toplevel)"
env_file="${repo_root}/.env"/
echo "env file: $env_file"

root_domain="$(cat ${env_file} | sed -n -e 's/^root_domain=//p')"

echo "root_domain: $root_domain"

function modify_template {
  if [ ! $# -ge 2 ]; then
    echo "Found less than 2 args"
    return
  fi

  local TEMPLATE_FILE="$1"
  local OUTPUT_FILE="$2"

  cat "$TEMPLATE_FILE" | \
    sed "s#\${root_domain}#${root_domain}#g" > "$OUTPUT_FILE" 
}

homer_root="${repo_root}/config/homer/instances"

modify_template "${homer_root}/public/config.template.yml" "${homer_root}/public/assets/config.yml"

modify_template "${homer_root}/private/config.template.yml" "${homer_root}/private/assets/config.yml"
```


@Roundaround  IMO best bet is to be unopinionated about which tokens to use, and to substitute any env var which matches a certain pattern, eg, with the prefix `HOMER_TEMPLATE`, maybe allow reading from file with `HOMER_TEMPLATE_FILE` so the following would work

```docker-compose
---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
      - '/your/api/keys/:/keys/:ro'
    ports:
      - 8080:8080
    environment:
        HOMER_TEMPLATE_root_tld: "example.com"
        HOMER_TEMPLATE_FILE_weather_api_key: "/keys/weather"
    restart: unless-stopped
```

For the config:

```yml
---

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Application"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Bookmark example"
        tag: "app"
        url: "blog.${root_tld}"
        target: "_blank" # optional html tag target attribute
  - name: "Weather"
    location: "Amsterdam" # your location.
    locationId: "2759794" 
    apikey: "${weather_api_key}" 
    units: "metric" 
    background: "square" 
    type: "OpenWeather"
```
