### ISSUE TITLE
Random background

### ISSUE THREAD

**Issue by lcardito** [bastienwirtz/homer#422]
Hey Team! First of all awesome work! Installed Homer today and I am already loving it!

I was basically looking to replace my new tab page with Homer from Momentum, one of the things I loved about Momento was the different background pic it would display every day. 

Trying to do something similar with Homer I came across [Picsum](https://picsum.photos/) which is extremely simple to integrate as the URL just returns an image. So I got:

```
    background-image: "https://picsum.photos/1920/1080"
```

in my Homer config and that works brilliantly!

Now, I am wondering, what if i wanted to be more fancy, like specify a topic or a collection? So I've found [UnSplash](https://unsplash.com/documentation#get-a-random-photo) which is even more awesome! 😄 

I am wondering if there's an interested of adding UnSplash as an integration for a random background functionality in Homer? 

Thanks!

**Comment by briancprice** [comment]
For anyone else that finds this like I did, 
You can add:
```
background-image: "https://source.unsplash.com/random/1920x1080/?wallpaper+desktop+background+cool"
```

**Comment by themicksters** [comment]
Hi, 

Could I have a snippet of your config file where you use the background-image instruction ? 
My configuration does not apply it, I guess I am not putting it in the proper position in the yaml file. 

thanks

**Comment by bastienwirtz** [comment]
@themicksters the background image can be set in the color section of the [configuration](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md): 

```yml
colors:
  light:
    background-image: "https://source.unsplash.com/random/1920x1080/?wallpaper+desktop+background+cool"
  dark:
    background-image: "https://source.unsplash.com/random/1920x1080/?wallpaper+desktop+background+cool"
```

I'm closing the issue as the solution as been found, feel free to reopen if anything.
