### ISSUE TITLE
Ping Module Feature Request

### ISSUE THREAD

**Issue by sujaldev** [bastienwirtz/homer#424]
I don't know if this is already possible but I'd like to separate out the url used by the ping service and the url that I am redirected to when I click on the service in the dashboard. Something like this:
```yaml
- name: "jellyfin"
      logo: "jellyfin.png"
      url: "https://jellyfin.example.com"
      target: "_blank"
      type: Ping
      ping_url: "https://health.example.com/jellyfin"
```
