### ISSUE TITLE
Scaling logo to cover title + subtitle 

### ISSUE THREAD

**Issue by fl0r1s** [bastienwirtz/homer#442]
Hi

Does anyone know how to scale the logo area to be the size of the banner?

thx!

**Comment by bastienwirtz** [comment]
Hey @fl0r1s, 

I think you could use a custom css file to do that, by adding somthing like 
```yml
stylesheet:
  - "assets/custom.css"
```

In your config file, with `custom.css` containing the tweak you want for your banner.

**Comment by fl0r1s** [comment]
Cool, I achieved this with the following:

``` css
body #bighead .first-line .logo img {
    max-width: 208px;
    max-height: 110px;
}
```
