### ISSUE TITLE
No config.yml when deployed on portainer.

### ISSUE THREAD

**Issue by deez3134** [bastienwirtz/homer#461]
Im new to this so how do i get the config.yml in assets

![image](https://user-images.githubusercontent.com/106639724/171314187-b41519f0-5834-4ff0-b3f3-613057d5e94d.png)

**Comment by wy580477** [comment]
Run following command:

mv config.yml.dist config.yml

**Comment by deez3134** [comment]
Thank you

**Comment by Hussienfahmy** [comment]
I have the same issue and the solution does not worked for me

**Comment by bastienwirtz** [comment]
Hi there, 

@deez3134 Config files should be automatically installed in your assets directory, IF you created the assets directory with the right permissions (same owner as the user runing the container). 

Could you share your container run parameter, the container startup logs, and show the assets directory permissions (`ls -la`) ?

**Comment by draz1c** [comment]
Hi,

I had same issue, but I didn't deploy it with Portainer (although a Portainer Docker is running in the machine) but with docker-compose.

I copied the [oficial docker-compose file](https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml) and edited it a bit to make traefik work (labels, and add the same network as traefik):

```yml
---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - './assets/:/www/assets'
    ports:
      - 8090:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    networks:
      - pi
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homer.rule=Host(`mycustomurl`)'
      - 'traefik.http.services.homer.loadbalancer.server.port=8080'
networks:
  pi:
    external: true
```

`mkdir assets` with default user (1000:1000) and `docker-compose up -d`.

Installation goes without errors, no failure logs. When it starts, docker logs show
```bash
2022-06-05 20:09:19: (server.c.1568) server started (lighttpd/1.4.64)
```

And I can access it, but the `assets` folder is empty.
