### ISSUE TITLE
Feature request: custom service from JSON (with mapping like in messages)

### ISSUE THREAD

**Issue by tushev** [bastienwirtz/homer#465]
Hello,

First, thanks for this wonderful app!

I would like to have an option to create a "custom service" only from API data, purely by config, without the need of [writing any code](https://github.com/bastienwirtz/homer/blob/main/docs/development.md).

Something like:

```yaml
      - name: "JSON API Service"
        logo: "assets/tools/sample.png"
        url: "http://my-service-link"
        endpoint: "http://api.example.com/api/v1/endpoint"
        type: "json"
        mapping:
          title: 'id'
          content: 'value'
```

I think that would be extremely useful and suitable for most of users.

**Comment by luixal** [comment]
Hi,

This is quite easy to implement, but I'm not sure which cases would be applicable to.

Do you any examples of what you have in mind?

**Comment by luixal** [comment]
Those are a good point.

One of the edge cases would be the auth part, maybe headers could be configured in the yaml config for this service.

The most difficult part would be to arrange info in the card. I guess we could make, as you put in your demo, mapping title, subtitle and indicator. If the indicator is not mapped, it would be used to show errors/state.

I have some sensors at home that could be used with something like this, and there are some public APIs that could be used too.

I'll give a try when I have some spare time :)

**Comment by tushev** [comment]
Great! Thanks!

I see this mostly as intended for APIs that do not require any authentication. Or maybe authentication support could be added later...

**Comment by luixal** [comment]
Hi,

I have worked out a first draft. I tested it using this APIs:

- [Chuck Norris Jokes](https://api.chucknorris.io/)
- [Excuser](https://excuser.herokuapp.com/)

configured like this:

```yaml
- name: "Api Json Services"
    icon: "fas fa-cloud"
    items:
      - name: "Chuck Norris Facts"
        logo: "https://api.chucknorris.io/img/chucknorris_logo_coloured_small@2x.png"
        type: "ApiJsonService"
        url: "https://api.chucknorris.io/jokes/random"
        mapping:
          subtitle: "value"
      - name: "Today's excuse"
        subtitle: "!!!"
        logo: "https://cdn.icon-icons.com/icons2/2248/PNG/512/alpha_e_circle_icon_137975.png"
        type: "ApiJsonService"
        url: "https://excuser.herokuapp.com/v1/excuse"
        mapping:
          subtitle: "excuse"
```

And they render this way:

![image](https://user-images.githubusercontent.com/615268/195904758-e5ab4c59-96ae-4c64-b21f-d77c5fe6dcef.png)

Thing is, when looking for other APIs with auth to add headers support, this faces problems like some APIs (like the excuser itself) return and array. I solved this by checking data type and, if array, take only the first item. But having a look around, other apis return always nested objects or even arrays nested into objects... this is, complex structures.

Not sure how many APIs could be used here.

Anyhow, if you see this as useful, let's wait for @bastienwirtz to think about it. If he's ok, I'll make the PR.
