### ISSUE TITLE
Pihole stats not displaying through a proxy URL

### ISSUE THREAD

**Issue by fmunteanu** [bastienwirtz/homer#478]
I'm using Nginx proxy to serve a friendly Pihole URL:

```
server {
    listen                    443 ssl http2;
    listen                    [::]:443 ssl http2;
    server_name               chaos.domain.com;
    index                     index.html;
    root                      /usr/share/nginx/html;
    proxy_buffering           off;
    proxy_redirect            off;
    proxy_set_header          Connection $http_connection;
    proxy_set_header          Host $host;
    proxy_set_header          Upgrade $http_upgrade;
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header          X-Forwarded-Proto $scheme;
    proxy_set_header          X-Real-IP $remote_addr;
    ssl_certificate           /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/domain.com/privkey.pem;
    ssl_trusted_certificate   /etc/letsencrypt/live/domain.com/chain.pem;
    ssl_protocols             TLSv1.3 TLSv1.2;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass            http://192.168.1.2/admin/;
    }
}
```

When I enter the following Homer configuration, I do not see the Pihole stats?

```
  - name: "Network"
    icon: "fas fa-server"
    items:
      - name: "chaos"
        type: "PiHole"
        logo: "assets/tools/pihole.png"
        tag: "dns"
        keywords: "dns pihole"
        url: "https://chaos.domain.com"
        target: "_blank"
```
