### ISSUE TITLE
Copy-to-Clipboard Option for Items

### ISSUE THREAD

**Issue by zekroTJA** [bastienwirtz/homer#500]
I think it would be awesome if you could copy predefined text to the clipboard instead of opening an URL. This could be useful especially for applications like Teamspeak Servers or Game Servers.

I would suggest adding a config key to the `Item` called something like `clipboard`. When defined, the text specified will be copied to the clipboard when clicking the item and a notification would pop up to indicate that the text has been copied. Also, there could be a little indicator on the item to show that the URL will be copied on clicking the item.

My current workaround "abuses" the `javascript` URL method, but I think it would be awesome if this would be supported natively.

```yml
- name: "Game Server"
    icon: "fas fa-gamepad"
    items:
      - name: "mc.zekro.de"
        subtitle: "Public Vanilla Minecraft Server"
        logo: "assets/tools/minecraft.png"
        keywords: "minecraft game ichigo"
        url: "javascript:navigator.clipboard.writeText('mc.zekro.de')&&alert('Address has been copied to the clipboard.')"
```

**Comment by luixal** [comment]
I see a couple of options for this feature:

1. An item having the `clipboard` field does copy that text to the clipboard when clicked. `url` field would do nothing.
2. Including an indicator: instead of using the indicator just as a visual help, maybe it would be better if clicking on the indicator copies the text in `clipboard` while clicking on the item open the `url`.
3. Same as 2 but instead of an indicator, make that `ctrl + click` copies and just clicking opens `url`

What do you think would be the best one?

**Comment by bastienwirtz** [comment]
Hi there, 

Thanks for the idea @zekroTJA 
For option 1, maybe a new "clipboard" service with a `content` property (or something like that) instead of `url` would be more explicit and simple to use? 
2nd option could works too, I'm just afraid the card become a bit crowded :thinking: 

I'm not a fan of option 3, as ctrl+click already open in a new tab.

**Comment by zekroTJA** [comment]
Hey, thank you very much for your feedback. 

I took a look into the code already and actually even started to implement a `clipboard` like card service but I was not sure how to style it properly that it will fit together with the UI of the other cards and contents. But yeah, I think that would be a nice option. I could also make a PR with my changes I have so far if you are interested and maybe you could work out the exact design as you want to have it. ^^

**Comment by luixal** [comment]
Yep, my bad on the ctrl+click thing. I use the click on the mouse wheel to open in new tab and forgot about this binding.

I think it can be useful to have both things on the same item. The copy icon can be placed on the #indicator slot and I think it could be nice.

It's not a lot of work, i'll put a minimal demo togheter and see how you feel about it :)

**Comment by luixal** [comment]
Hi,

I've done something quite similar to what I last commented. It is configured like this:

```yaml
- name: "Copy me"
  logo: "assets/tools/sample.png"
  subtitle: "some text goes here"
  tag: "test"
  url: "#"
  type: "CopyToClipboard"
  clipboard: "aloha!"
```

so you can show a title and a subtitle, open an url on click and copy the content in the `clipboard` field when the icon is click. It looks like this:

![image](https://user-images.githubusercontent.com/615268/194855277-0fa76e01-6c8a-44af-88e0-183326144e92.png)

I haven't found a way to show a notification at the main page level (maybe @bastienwirtz has any comment on this) so I look for a workaround and make the clipboard icon to animate and change color for a couple of seconds after it's clicked:

![chrome-capture-2022-9-10](https://user-images.githubusercontent.com/615268/194855506-2a4750f8-851f-401e-874e-b1843fcdcf3f.gif)

What do you thing?

**Comment by zekroTJA** [comment]
Yeah, I also had something similar to this in mind. Looks great in my opinion.

**Comment by bastienwirtz** [comment]
Hello, 

The clipboard custom service is now available thanks to @luixal !

Best,

**Comment by tekwarfare** [comment]
This is super neat but I can't actually copy anything to the clipboard. The icon, tag, and hover event events all work as they should. I'm using Firefox (112.0).

**Comment by luixal** [comment]
Hi @tekwarfare , just tested it on Firefox 112.0 (64bits) with the example config as is working for me:

```yaml
- name: "Copy me!"
  logo: "assets/tools/sample.png"
  subtitle: "Subtitle text goes here"
  url: "#"
  type: "CopyToClipboard"
  clipboard: "this text will be copied to your clipboard"
```

Can you post your config for this service?
