### ISSUE TITLE
Defaults are ignored when not using navbar

### ISSUE THREAD

**Issue by erdemoney** [bastienwirtz/homer#527]
If I disable the navbar by using an empty links section like this 
```
...
links:

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'
...
```

Columns layout is still used despite being set to 'list'
