### ISSUE TITLE
Some problems with 2 services

### ISSUE THREAD

**Issue by Lindwen** [bastienwirtz/homer#529]
I use docker to put all these services into production.
For more informations :
The container Homer and Portfolio are on the same stack in a network in bridge mod.
Logs : 
```bash
docker logs homer
Starting webserver
2022-10-13 12:34:47: (server.c.1568) server started (lighttpd/1.4.64)
```

---------------------------------------------------------------------------
# Ping service 
```yml
      - name: "Homer"
        icon: "fa-solid fa-house"
        subtitle: "homer.*****.**"
        tag: "website"
        url: "#"
        type: Ping
        method: "head"
      - name: "Portfolio"
        icon: "fa-solid fa-user"
        subtitle: "www.*****.**"
        tag: "website"
        url: "https://www.*****.**"
        target: "_blank"
        type: Ping
        method: "head"
```
The first service `Homer` is print online, and the second `Portfolio` is print offline (but online in reality).

# Portainer service
```yml
 - name: "Portainer"
    icon: "fa-brands fa-docker"
    url: "https://portainer.*****.**/"
    type: "Portainer"
    apikey: "*****"
    subtitle: "portainer.*****.**"
    tag: "website"
    target: "_blank"
```
This service don't print anything.
