### ISSUE TITLE
Method property of ping service is not optional

### ISSUE THREAD

**Issue by Tooa** [bastienwirtz/homer#530]
Hi :wave:,

in this [pull request](https://github.com/bastienwirtz/homer/pull/484) @isuttell introduced the the new [optional](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md#ping) `method` configuration for the ping service. With `homer:22.10.1` the following error occurs when the `method` property is not set in the configuration: 

```bash
Ping: unknown is not a supported HTTP method 15 [Ping.29309501.js:formatted:41](https://<redacted>resources/Ping.29309501.js:formatted)
    fetchStatus Ping.29309501.js:41
    created Ping.29309501.js:33
    hn index.12daa1ad.js:1
    je index.12daa1ad.js:1
    je index.12daa1ad.js:1
```

The issue was introduced in [this](https://github.com/bastienwirtz/homer/commit/84930a632b7133ad48c3078a2449bb7b82b191d4) commit while adding a more strict type checking.

## Steps to reproduce

`config.yml`
```yml
- name: "Exporter"
   logo: "assets/tools/prometheus.png"
   tag: "app"
   url: "https://<redacted>"
   type: "Ping"
   target: "_blank"
```

## Debugging information

![homer_ping_method_1](https://user-images.githubusercontent.com/5375334/195844538-c60cf627-0354-45ba-8133-5179decf1029.png)
