### ISSUE TITLE
Proxmox card cutting off info

### ISSUE THREAD

**Issue by CreationGuy** [bastienwirtz/homer#531]
Per @luixal I am submitting this issue. 
On small screens the data is cut off. Here's an example: https://i.postimg.cc/fy0CBv4z/Screenshot-2022-10-14-at-13-19-43-207-LAN-net-Dashboard-Intranet.png

**Comment by jimbytes** [comment]
It will be nice to optimize the Proxmox Card, here are some suggestions:
- Please add LXC containers count
- Remove the decimal (.x) on values, use whole number. (45.7% = 46%)
- It would be nice to show what we want, a way to select values. In the YAML file, it could be like:  show: [“cpu”, “vms”, “ct”]

**Comment by bastienwirtz** [comment]
Hi there, 

I think @luixal, the author of the Proxmox card is working on it!

**Comment by luixal** [comment]
Hi,

Yes, I'm working on this :)

As it seems many people is interested in this service (didn't know so much people used both, homer and proxmox!) i'll make some of these changes configurable (like showing decimals or not).

I'll post some of the changes here, before making a PR.

Cheers!

**Comment by luixal** [comment]
Hi,

I've added three new options:

```yaml
small_font_on_small_screens: true # uses a smaller font for subtitle on small screens
hide_decimals: true # removes decimals from stats values.
hide: ["vms", "lxc", "disk", "mem", "cpu"] # hides values included in the array
```

Also, when no VMs exist in Proxmox, that value is hidden by default.

Due to this config values directly impact on the layout, I removed the `flex` with `space-between` justification from CSS. Now all values are shown in line, with some margin between them. Spacing in full width with only 2 or 3 values looked really ugly.

I will add the LCX value, but I need to create some of them. The same rule for auto-hidding VMs will be applied to this containers.

Will make a PR as soon as I got it implemented.

**Comment by luixal** [comment]
This has totally gone mad... maybe now it's too much configurable xD

These are the final options, I think they're self explanatory:

```yaml
small_font_on_small_screens: true
small_font_on_desktop: true
hide_decimals: true
hide: ["vms", "vms_total", "lxc", "lxcs_total", "disk", "mem", "cpu"]
```

You can achieve things like in this examples (screenshot according to config below):

### ALL info with small font on desktop
![image](https://user-images.githubusercontent.com/615268/196228881-b890aaa0-38b8-4796-8403-d47fa0c0361a.png)

```yaml
small_font_on_small_screens: true
small_font_on_desktop: true
hide_decimals: true
```

### Some info about general status
![image](https://user-images.githubusercontent.com/615268/196229349-6a7d06f5-d8e0-4f9b-807c-71f3779af0ea.png)

```yaml
small_font_on_small_screens: true
hide_decimals: true
hide: ["vms", "vms_total", "lxc", "lxcs_total"]
```

### ALL info but VMs and LCXs totals
![image](https://user-images.githubusercontent.com/615268/196229662-743e4a39-0796-4702-aa69-0978c5d1a6ba.png)

```yaml
small_font_on_small_screens: true
# small_font_on_desktop: true
hide_decimals: true
hide: ["vms_total", "lxc_total"]
```

I'll update the docs and make the PR.
