### ISSUE TITLE
YAML anchoring doesn't work anymore?

### ISSUE THREAD

**Issue by Noukkis** [bastienwirtz/homer#559]
Hi,

I tried using this minimal example, inspired by the [tips and tricks](https://github.com/bastienwirtz/homer/blob/main/docs/tips-and-tricks.md#yaml-anchors) section:

```yaml
---
tags:
  Apps: &Apps
    - tag: "App"
      tagstyle: "is-medium is-info"

services:
  - name: Applications
    items:
      - name: "VS Code"
        <<: *Apps
        url: "https://vscode.example.com/"
```

and the tags doesn't appear on the item.

But when I put the json equivalent in config.yml:
```json
{
  "services": [
    {
      "items": [
        {
          "url": "https://vscode.example.com/", 
          "tag": "App", 
          "name": "VS Code", 
          "tagstyle": "is-medium is-info"
        }
      ], 
      "name": "Applications"
    }
  ], 
  "tags": {
    "Apps": [
      {
        "tag": "App", 
        "tagstyle": "is-medium is-info"
      }
    ]
  }
}
```

then it works as expected.

Has there been a regression somewhere that made anchoring not work anymore, or am I doing things incorrectly?
