### ISSUE TITLE
Since version 22.10, tags with target no longer work.

### ISSUE THREAD

**Issue by DocBrown101** [bastienwirtz/homer#566]
This describes how to deal with "tags":
https://github.com/bastienwirtz/homer/blob/main/docs/tips-and-tricks.md

I use this function additionally with target: '_blank'

```yaml
tags: 
  Apps: &Apps
    - tag: "App"
      tagstyle: "is-small is-primary"
      target: '_blank'
````

```yaml
- name: "VS Code"
  logo: "/assets/vscode.png"
  subtitle: "Develop Code Anywhere, On Anything!"
  <<: *Apps # Reference to the predefined "App" Tag
  url: "https://vscode.example.com/"
````

Since version 22.10 _blank is ignored and all links open in the same tab.
