### ISSUE TITLE
Proxmox custom service does not display info on tile

### ISSUE THREAD

**Issue by marcogiorgio** [bastienwirtz/homer#568]
Hi,
I have the latest docker image of Homer and I am trying to set up the Proxmox integration. I added the X-allow-origin header to my rev proxy that serves Proxmox URL, I have no CORS errors on my browser console and I can see that Homer does the HTTP call and gets a correct response from Proxmox as you can see here
<details>
<summary>HTTP response</summary>

```json
{
	"data": {
		"uptime": 433992,
		"memory": {
			"used": 32757219328,
			"total": 67186819072,
			"free": 34429599744
		},
		"wait": 0.00125960198976719,
		"idle": 0,
		"loadavg": [
			"0.88",
			"0.85",
			"0.97"
		],
		"swap": {
			"used": 0,
			"total": 8589930496,
			"free": 8589930496
		},
		"ksm": {
			"shared": 0
		},
		"cpuinfo": {
			"user_hz": 100,
			"cores": 10,
			"mhz": "2800.000",
			"model": "Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz",
			"hvm": "1",
			"cpus": 20,
			"sockets": 1,
			"flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke sgx_lc md_clear flush_l1d arch_capabilities"
		},
		"pveversion": "pve-manager/7.3-3/c3928077",
		"kversion": "Linux 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100)",
		"cpu": 0.0515762083791526,
		"rootfs": {
			"used": 8537169920,
			"avail": 87153819648,
			"total": 100861726720,
			"free": 92324556800
		}
	}
}
```
</details>
However, the only thing I see on the Dashboard is this:

![dashboard view](https://user-images.githubusercontent.com/78936558/206765310-6fc35b05-24a0-46ed-ac6f-bb1f9ef6083a.png)

The .yaml config for Homer is this one:
<details>
<summary> YAML config </summary>

```yaml
- name: "Server and Storage"
    icon: "fas fa-hdd"
    items:
      - name: "Proxmox VE"
        logo: "assets/tools/png/proxmox.png"
        tag: "app"
        url: "https://proxmoxve.EXAMPLE.COM"
        type: "Proxmox"
        node: "pve" 
        warning_value: 50
        danger_value: 80
        api_token: "PVEAPIToken=root@pam!TOKENNAME=TOKENVALUE"
        # values below this line are optional (default value are false/empty):
        hide_decimals: true # removes decimals from stats values.
        hide: ["vms", "vms_total", "lxcs", "lxcs_total", "disk", "mem", "cpu"] # hides values included in the array
        small_font_on_small_screens: true # uses small font on small screens (like mobile)
        small_font_on_desktop: true # uses small font on desktops (just in case you're showing much info)
```
</details>

Does anyone know what the problem can be?
Thanks
