### ISSUE TITLE
PiHole stats not available in Homer if WebUI is password protected

### ISSUE THREAD

**Issue by fmunteanu** [bastienwirtz/homer#579]
### Describe the bug

Everything is functional, except PiHole stats are not displayed. There are no CORS related errors, I fixed the issue into #478.

### Expected behaviour

PiHole stats show in Homer.

### Logs & errors

PiHole runs on a dedicated Raspberry Pi and stats show, when called directly:

![image](https://user-images.githubusercontent.com/19806136/209587612-04434d90-6026-4492-963f-99a54fb29d2b.png)

Browser console shows no errors:

![image](https://user-images.githubusercontent.com/19806136/209587439-87797bca-ec73-4916-b207-27dfe9ed15d2.png)

PiHole.abc61540.js Preview

![image](https://user-images.githubusercontent.com/19806136/209587497-c92dec88-15cc-43d2-ae58-ecd5dacbbd20.png)

PiHole.abc61540.js Headers

![image](https://user-images.githubusercontent.com/19806136/209587582-e04303ef-72a7-4073-866a-b99de314cb07.png)

### Configuration

![image](https://user-images.githubusercontent.com/19806136/209587649-606e80a6-f686-4587-b4e3-ffa53445c943.png)

```yml
services:
  - name: "Network"
    icon: "fas fa-server"
    items:
      - name: "chaos.lan"
        type: "PiHole"
        logo: "assets/tools/pihole.png"
        tag: "dns"
        keywords: "dns pihole"
        url: "http://chaos.lan/admin/"
```
