### ISSUE TITLE
PiHole Unusual CORS error

### ISSUE THREAD

**Issue by PedroC1999** [bastienwirtz/homer#582]
**Describe the bug**
I am using Nginx/Authelia to protect and reverse proxy my services. I have been using appropriate headers within my nginx configuration (working for 3 other services). mydomain.com/admin/api.php is accessible and displays the JSON format correctly. However I get a syntax error in the chrome dev console which indicates a  CORS error message got sent instead of the JSON file, however Chrome has not filed this as the usual red "error".

**Expected behavior**
No errors and for the service to work

**Logs & errors**
```
SyntaxError: Unexpected token 'F', "Failed COR"... is not valid JSON PiHole.abc61540.js:1 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status') at Proxy.fetchStatus (PiHole.abc61540.js:1:536)
```

**Configuration**
```nginx
        if ($request_method ~* "(GET|POST|FETCH)") {
            add_header "Access-Control-Allow-Origin"  *;
        }

        if ($request_method = OPTIONS ) {
            add_header "Access-Control-Allow-Origin"  *;
            add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept,X-Api-Key";
            return 200;
        }
```
```yml
      - name: "PiHole"
        icon: "fas fa-ban"
        tag: "app"
        ##target: "_blank" # optional html a tag #target attribute
        url: "https://pihole.domain.xyz/admin/"
        type: "PiHole"
        apikey: "aacf0920ab9f9e2a82457e5apikeyhere37b304a263f9f27f30e51206d09b0db"
```
