### ISSUE TITLE
Randomly  shows  offline error  on gitlab pages

### ISSUE THREAD

**Issue by rizerzero** [bastienwirtz/homer#586]
**Describe the bug**
Hi, I sometimes get the message "your're offline friend" randomly 
I'm currently using GitLab pages for hosting, and sometimes it randomly gives the error message and then I have to refresh to get the pages again. I'm not sure why this is happening, I get some random error in the console but this is not clear, I have no similar issues with other static documentation like Mkdocs using GitLab pages. 

Note that the GitLab page is secured and I'm authorized, it just randomly shows the error and sometimes gives me a 401, only with homer.

**Expected behavior**
Correct display of pages 

**Logs & errors**

![image](https://user-images.githubusercontent.com/1518379/212309705-2389ccf6-dcce-4f7c-9a59-3e8251390764.png)
**Configuration**

```yml
site_name: example
site_author: example
copyright: example 
strict: true
theme:
  language: en
  direction: ltr
  favicon: assets/img/favicon.ico
  name: material
  logo: assets/img/logo.png
  features:
    - navigation.tabs
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: default
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
 
  hide:
    - navigation
nav:
  - Home: 
    - index.md
  
# Markdown Extension
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date

extra_css:
  - assets/css/extra.css
```
