### ISSUE TITLE
Firefox Recieving Different HTML compared to Chrome

### ISSUE THREAD

**Issue by Moulik-Budhiraja** [bastienwirtz/homer#600]
**Describe the bug**

Firefox receives different HTML. Specifically, the firefox version doesn't contain wrapping div's for each service group.

I have tried following all steps on [Websites look wrong or appear differently than they should](https://support.mozilla.org/en-US/kb/websites-look-wrong-or-appear-differently) but none of the steps made a difference.

**Expected behavior**

I expect each group to be organized into a column like in chrome.

**Logs & errors**
Please include any usefull information:
- Errors in your browser console (`ctrl+shift+i` or `F12`)
- If applicable, your docker container logs.

None

**Screenshots**

### Chrome

![chrome](https://user-images.githubusercontent.com/79997562/217413170-9258df13-2290-43ef-9728-b3f68f666726.png)

### Firefox

![firefox](https://user-images.githubusercontent.com/79997562/217413219-cf18b75c-1d03-48b1-9cef-7fe92eb37311.png)

**Configuration**
If applicable, copy related homer yaml configuration here.

### config.yml
```yml
---

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"

stylesheet:
  - "assets/custom.css"

columns: 3
connectivityCheck: true

# defaults:
#   layout: "columns" # Either 'columns', or 'list'

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"


# navbar
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page"

# Services
services:
  - name: "Automation"
    items:
      - name: "Home Assistant"
        logo: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo.png"
        url: "http://192.168.50.232:8123
        endpoint: "http://192.168.50.232:8030/http://192.168.50.232:8123"
        target: "_blank"
        type: Ping

      - name: "Homebridge"
        logo: "https://raw.githubusercontent.com/homebridge/branding/master/logos/homebridge-color-round-stylized.png"
        url: "http://192.168.50.232:8581/"
        endpoint: "http://192.168.50.232:8030/http://192.168.50.232:8581/"
        target: "_blank"
        type: Ping

      - name: "qBittorrent"
        logo: "assets/tools/qbittorrent.svg"
        url: "http://192.168.50.232:9080/"
        endpoint: "http://192.168.50.232:8030/http://192.168.50.232:9080"
        target: "_blank"
        type: Ping

  - name: "Routing"
    items:
      - name: "Router"
        logo: "http://192.168.50.1/images/favicon.png"
        url: "http://192.168.50.1/Main_Login.asp"
        endpoint: "http://192.168.50.232:8030/http://192.168.50.1/Main_Login.asp"
        target: "_blank"
        type: Ping

      - name: "Nginx"
        logo: "https://raw.githubusercontent.com/NginxProxyManager/nginx-proxy-manager/develop/frontend/app-images/logo-256.png"
        url: "http://192.168.50.232:81/"
        endpoint: "http://192.168.50.232:8030/http://192.168.50.232:81/"
        target: "_blank"
        type: Ping

  - name: "Media"
    items:
      - name: "qBittorrent"
        logo: "assets/tools/qbittorrent.svg"
        url: "http://192.168.50.232:9080/"
        endpoint: "http://192.168.50.232:8030/http://192.168.50.232:9080"
        target: "_blank"
        type: Ping

```

### custom.css

```css
@charset "UTF-8";
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap");

:root {
    --status-online: #94e185;
    --status-offline: #c9404d;
}

body .no-footer #main-section {
  display: flex;
  flex-grow: 1;
}
body #app {
  display: flex;
  flex-direction: column;
}

footer {
  display: none;
}
body,
h1,
h2,
p,
.title {
  font-family: Open Sans !important;
  font-weight: 400 !important;
}

p.title {
  font-weight: 700 !important;
}

nav {
  display: none !important;
}
body #bighead .first-line .logo img {
  border-radius: 50%;
}
body #app .card,
body #app .card:hover,
body #app .message {
  box-shadow: unset;
}
body .card {
  box-shadow: unset;
  border-radius: 10px;
}
body #app .card {
  border-radius: 10px;
}
.status :not(::before) {
  display: none;
}
.image.is-48x48 {
  width: 36px;
  height: 36px;
}
.status.online,
.status.offline {
  position: absolute;
  right: 12px;
  font-size: 0 !important;
  color: var(--background) !important;
}
.column > div {
  margin-bottom: 1.8em;
}

.card-content {
  height: 100% !important;
}

.status.offline::before {
  background-color: var(--status-offline) !important;
  border: unset !important;
  box-shadow: 0 0 5px 1px var(--status-offline) !important;
}

.status.online::before {
  background-color: var(--status-online) !important;
  border: unset !important;
  box-shadow: 0 0 5px 1px var(--status-online) !important;
}

```
