### ISSUE TITLE
Unknown variable dynamic import when trying to add qBittorrent custom service

### ISSUE THREAD

**Issue by powaful** [bastienwirtz/homer#604]
**Describe the bug**
Trying to add qBittorrent custom service, but facing `Error: Unknown variable dynamic import: ./services/qBittorrent.vue` error in browser console

**Expected behavior**
No errors

**Logs & errors**
Please include any usefull information:
- Error: Unknown variable dynamic import: ./services/qBittorrent.vue
- Docker container logs do not show anything

**Screenshots**
![image](https://user-images.githubusercontent.com/3275818/220121164-8b6b8cf0-cd12-4b7c-9f81-706593304857.png)

**Configuration**
```yml
  - name: "//Applications"
    items:
      - name: "qBitTorrent"
        type: "qBittorrent"
        rateInterval: 2000
        torrentInterval: 5000
        url: "http://192.168.1.2:8080"
        target: "_blank"
```

Dashboard is on the same network.
