### ISSUE TITLE
CORS seems to be kept enabled for Portainer after removing the custom service.

### ISSUE THREAD

**Issue by schumi2004** [bastienwirtz/homer#606]
I tried to fetch data from my portainer instance using the custom service.
Eventually played with CORS headers without luck so i tried to revert the config but now my item in homer dashboard keeps adding the portainer fqdn behind the one from homer, like this:

https://homer.mydomain.com/portainer.mydomain.com

No matter what i do it keep doing this.

Tried multiple browsers already, cleard cache etc but it won't revert back to like it is configured.

      - name: "Portainer"
        logo: "assets/icons/tools/portainer.png"
        subtitle: "Hybrid & multi-cloud container management platform"
        url: "https:/portainer.mydomain.com"
        tag: "tools"
        target: "_blank"

I had other custom services configured like this but they all reverted back to normal but not for portainer.

Any ideas?

**Comment by SirMartin** [comment]
I have issues also configuring portainer with the apikey. I got CORS issue, and it is the only one. Works fine for Sonarr, Radarr, PiHole, etc.

**Comment by bursaar** [comment]
I think it's because you only have one `/` after the `https:` in the url.

**Comment by thibaut1304** [comment]
Hi! I know this issue is quite old, but since it's still open, I thought I'd chime in :)

The problem is indeed related to CORS. Some services don’t require headers to work — for example Radarr, which passes the API key directly in the URL (?apikey=...).

Others, however, like Proxmox (which needs Authorization) or Portainer (which uses x-api-key), require specific HTTP headers — so you need to explicitly allow them in your reverse proxy.

Personally, I use Traefik, and here’s an example of a CORS middleware I applied to my routes:

```yaml
http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "https://votre-domaine.com"    # à adapter
          - "http://localhost:5173"
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "x-api-key"
          - "Content-Type"
          - "Accept"
        accessControlExposeHeaders:
          - "Authorization"
          - "x-api-key"
        accessControlMaxAge: 100
        addVaryHeader: true
```

Hope this helps someone out there! :hammer_and_wrench:
