### ISSUE TITLE
Passing secrets or env vars to the config.yaml

### ISSUE THREAD

**Issue by denysdovhan** [bastienwirtz/homer#609]
**Is your feature request related to a problem? Please describe.**

Hey! Thanks for this project!

Is there a way to pass secrets into `config.yaml` file via some sort of keyword?

**Describe the solution you'd like**

For example, Home Assistant and zigbee2mqtt projects provide an ability to pass secrets or env vars via keywords in a YAML files. Like this:

```yaml
token: !env TOKEN_ENV_VARIABLE
# or
token: !secret token # token field from secrets.yaml file
```

**Describe alternatives you've considered**

¯\_(ツ)_/¯ 

**Additional context**

I am open sourcing my [smart home config](https://github.com/denysdovhan/smart-home) and would like to use Homer for a dashboard of my smart home server. I would love to publish my config, by I also need to pass some secrets to the config (like token for Portainer or Pi Hole, etc)
