### ISSUE TITLE
Lighthttpd logs

### ISSUE THREAD

**Issue by nicolas-brousse** [bastienwirtz/homer#616]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to configure a docker swarm stack with Homer Dashboard behind a traefik proxy, but homer respond to me with 400 Bad Request.
Lighthttpd doesn't show log so it's not easy to me to know what is the exact issue.

**Describe the solution you'd like**
Update lighthttpd to log access and may be errors (if possible).

**Describe alternatives you've considered**
-

**Additional context**

Here the stack description I've tried to use
```yml
# homer.stack.yml

version: "3"
services:
  homer:
    image: b4bz/homer:v23.02.2
    volumes:
      - /mnt/glusterfs/homer_dashboard/assets:/www/assets
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homer_dashboard.rule=Host(`homer_dashboard.swarm.home`)"
        - "traefik.http.routers.homer_dashboard.entrypoints=http"
        - "traefik.http.services.homer_dashboard.loadbalancer.server.port=8080"
```
