### ISSUE TITLE
[Question] Information about pihole dont show

### ISSUE THREAD

**Issue by Vctrsnts** [bastienwirtz/homer#628]
**Describe the bug**
Is not a bug, Im trying to watch the statics off pihole in subtitule but not show.

**Expected behavior**
I read the costumerservice and create the section about pihole, create a file api.php and put on **dummy-data>pihole** say:
 - create a directory for your service, and any sub-folder existing in the service api path.
 - save the api output in a file named after the service endpoint._

I have a directory in assets with name **pihole** and in have **api.php** with this [configuration](https://github.com/bastienwirtz/homer/tree/main/dummy-data/pihole) 

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
      - name: "Pi-hole"
        logo: "assets/tools/pihole.png"
        tag: "management"
        #subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        url: "http://my.private.ip:my.port/admin"
        apikey: "my.api.key"
        type: "PiHole"
        target: "_blank"
```

My question is where is the problem because I dont now.

Thanks
