### ISSUE TITLE
Adguard Home Stats Unknown Status 403 

### ISSUE THREAD

**Issue by moritz-hoelting** [bastienwirtz/homer#631]
**Describe the bug**
The Status of Adguard Home is shown as Unknown, even after allowing setting CORS Headers in Traefik. In the console status 403 Forbidden is shown and after some research I found out that this is happening because of the missing session cookie.

But my problem is, I haven't found a way to change the homer configuration to get the stats with username and password.

**Expected behavior**
Status being shown correctly

**Configuration**

```yml
items:
      - name: "AdGuard Home"
        icon: "fas fa-rectangle-ad"
        url: "https://URLTOMYADGUARDINSTANCE"
        target: "_blank"
        type: "AdGuardHome"
```

**Comment by ciddi89** [comment]
Have the same issue. But if I click on the link in the web inspector, where Homer is trying to fetch the data. Can I read the raw data. So it is available.

**Comment by moritz-hoelting** [comment]
> Have the same issue. But if I click on the link in the web inspector, where Homer is trying to fetch the data. Can I read the raw data. So it is available.

I looked there too, but I only got the response _Forbidden_

**Comment by muzzymate** [comment]
I just struggled with this but finally got it working last night. You'll also need to use your reverse proxy to inject an authorization header. Here is a PR that will add instructions on how to do it with NGinx Proxy Manager, which is what I use. I'd imagine there are similar commands for Traefik.

https://github.com/bastienwirtz/homer/pull/450/commits/5b35596e426971f8bfc4c1dd7b2792a0074ba298

**Comment by djusHa** [comment]
Why it's not possible to set a header to Adguard Service like this:

```
- name: "Adguardd"
        logo: "assets/tools/igit/svg/adguard-home.svg"
        url: "https://adguard.home.lan"
        target: "_blank"
        type: "AdGuardHome"
        headers:
          Authorization: "Basic <YOURBASE64ENCODEDCREDS>"
```
