### ISSUE TITLE
Add custom headers per service

### ISSUE THREAD

**Issue by h3ku** [bastienwirtz/homer#646]
**Is your feature request related to a problem? Please describe.**
I want to use some of the custom services, however my services are behind Cloudflare access so when server.com tries to call test.sever.com its presented with a Cloudflare access HTML page.

**Describe the solution you'd like**
I can create access tokens to be used in the request headers. I want to pass this custom headers to the service worker. A potential implementation could be.

```
- name: "Radarr"
  type: "Radarr"
  url: "http://localhost:7878/"
  apikey: "<---insert-api-key-here--->"
  headers: 
    - Authorization: "xxxxxx"
    - x-header: "xxxxxx"
  target: "_blank"
  legacyApi: true
```

**Describe alternatives you've considered**
I been playing around with CORS but there is no way to fix it easily (Lots of people have similar issues in cloudflare forums and the recommendation is Cloudflare workers which I think its overkill for this)
