### ISSUE TITLE
Custom icons do not work (403 Forbidden)

### ISSUE THREAD

**Issue by knuurr** [bastienwirtz/homer#660]
**Describe the bug**
Custom icons mounted under "/www/assets/tools" docker-Compose do not work.

I wanted to supply container with custom icons for my apps.
Here's snippet of my mount from docker-compose:
```
    container_name: homer
    volumes:
      - /opt/homer:/www/assets
      - ./icons/png:/www/assets/tools
```
![obraz](https://github.com/bastienwirtz/homer/assets/135069967/1033b579-15bb-44b4-b079-2579f473d5cd)

I ensured files are accesible form within container - I did `cat` on one of files inside container:

![obraz](https://github.com/bastienwirtz/homer/assets/135069967/f8eb6932-cf1b-42e1-a3df-c9ce3709ab9f)

But inside dashboard, only alt text is displayed:

![obraz](https://github.com/bastienwirtz/homer/assets/135069967/46305286-1d5f-42b9-a522-46ac98e4bbff)

I decided to inspect one of links which leads to thumbnail, and I discovered link returns 403 Forbidden

`assets/tools/traefik.png`
![obraz](https://github.com/bastienwirtz/homer/assets/135069967/d39c4c7e-f261-41d7-84fa-906168365c45)

I don't know why it's happening. For me, config looks ok and functional. Along with references to img files:

```
services:
  - name: "Dashboards"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Traefik Dashboard"
        logo: "assets/tools/traefik.png"
        url: "https://traefik.europa.local"
        subtitle: "Another application"
        tag: "app"
        target: "_blank" 
```

When I unmount my custom `tools` folder with custom icons and restart container, exmaple icon loads just fine (I have it configured for one of apps):

![obraz](https://github.com/bastienwirtz/homer/assets/135069967/ae9c889e-e04d-4bcb-bf90-c27baf027b7c)

**Expected behavior**
Icons display just fine - just like provided with app examlpe icons.

**Logs & errors**
Please include any usefull information:
- Errors in your browser console (`ctrl+shift+i` or `F12`)
- If applicable, your docker container logs.
There isn't anything useful in logs
```text
Starting webserver

2023-06-16 19:31:34: (server.c.1568) server started (lighttpd/1.4.64)

2023-06-16 19:31:34: (server.c.2077) server stopped by UID = 0 PID = 0

Starting webserver

2023-06-16 19:31:36: (server.c.1568) server started (lighttpd/1.4.64)
```

**Screenshots**

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
services:
  - name: "Dashboards"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Traefik Dashboard"
        logo: "assets/tools/traefik.png"
        url: "https://traefik.europa.local"
        subtitle: "Another application"
        tag: "app"
        target: "_blank
```
