### ISSUE TITLE
Start Android or IOS APP from Homer

### ISSUE THREAD

**Issue by udomichel** [bastienwirtz/homer#668]
Maybe also as a custom service? 
Don't know if it's possible, but it seemed to be doable:
https://levelup.gitconnected.com/how-to-launch-any-mobile-app-from-the-web-1ad785a0e0a6

**Comment by SpeakingOfBrad** [comment]
That's already possible on iOS. Just set the url to whatever the url/scheme/thing for that app is.
For example:
```
  - name: "Home Automation"
    icon: "fas fa-house-signal"
    items:
      - name: "Home Assistant"
        logo: "assets/icons/homeassistant.svg"
        url: "http://homeassistant.local:8123/"
      - name: "Home Assistant App"
        logo: "assets/icons/homeassistant.svg"
        url: "homeassistant://"
```
The first link will open Home Assistant in the browser, and the second link will open the Home Assistant iOS app.
