### ISSUE TITLE
Error on using filter when a group contains no items

### ISSUE THREAD

**Issue by Xavinooo** [bastienwirtz/homer#682]
**Describe the bug**
When a group contains no items, like :
```
services:
  - name: "Core"
    icon: "fas fa-server"
    items:
```

when using the search, there is an error, and no search : 

![image](https://github.com/bastienwirtz/homer/assets/113215765/42014aab-c271-40ae-9a91-c3882c90b8e2)

**Expected behavior**
Ignore empty groups when searching so it does not crash
