### ISSUE TITLE
Tautulli custer service not working

### ISSUE THREAD

**Issue by Ashkaan** [bastienwirtz/homer#684]
**Describe the bug**
Homer just shows an error icon.

**Expected behavior**
I should see the current status of my Plex server.

**Logs & errors**
Please include any usefull information:
See screenshots:

**Screenshots**
Error in Homer
<img width="261" alt="image" src="https://github.com/bastienwirtz/homer/assets/5667978/97516a82-0e90-4baf-a6be-8e42351d3955">
Tautulli Log when I access Homer
<img width="947" alt="image" src="https://github.com/bastienwirtz/homer/assets/5667978/eaeb41fc-4dc0-41a4-97ff-f6cd26df0ed6">

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
- name: "Tautulli"
  logo: "<logo>"
  url: "http://<ip>:<port>"
  type: "Tautulli"
  apikey: "<key>"
```
