### ISSUE TITLE
Proxmox custom service not working

### ISSUE THREAD

**Issue by Ashkaan** [bastienwirtz/homer#685]
**Describe the bug**
Homer says "Loading..." and just spins and then eventually times out to an error.

**Expected behavior**
I should see the current status of my Proxmox server.

**Logs & errors**
Please include any usefull information:
See screenshots:

**Screenshots**
Issue in Homer
![image](https://github.com/bastienwirtz/homer/assets/5667978/1c5fef66-c78b-4d30-b579-cd634ddbd3c9)
<img width="324" alt="image" src="https://github.com/bastienwirtz/homer/assets/5667978/5ffb9905-9017-4312-84f6-fa9cac86eac4">

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
      - name: "Proxmox-1A"
        logo: "assets/images/proxmox.png"
        type: "Proxmox"
        <<: *hardware
        keywords: "server"
        url: "https://<IP>:8006"
        node: "proxmox-1a"
        warning_value: 50
        danger_value: 80
        api_token: "PVEAPIToken=<user>@<realm>!<token>=<secret>"
        target: "_blank"
```
