### ISSUE TITLE
Uptime Kuma custom service not working

### ISSUE THREAD

**Issue by Ashkaan** [bastienwirtz/homer#686]
**Describe the bug**
No extra data shows under Uptime Kuma.

**Expected behavior**
I should see the current status of my Uptime Kuma issues.

**Logs & errors**
Please include any usefull information:
See screenshots:

**Screenshots**
<img width="325" alt="image" src="https://github.com/bastienwirtz/homer/assets/5667978/82801fee-d9fa-4944-b4c9-8a8d92f618bf">

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
      - name: "Uptime Kuma"
        logo: "assets/images/uptimekuma.png"
        type: "UptimeKuma"
        url: "<status page>"
```
