### ISSUE TITLE
Search fails on dashboards with empty groups

### ISSUE THREAD

**Issue by vlorian-de** [bastienwirtz/homer#691]
**Describe the bug**
When having an empty group in a dashboard, all searches will fail and the error "TypeError: n.items is not iterable" is thrown in the console.

**Expected behavior**
Search should also work on dashboards with empty groups.

**Configuration**
```yml
---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "Empty Group"
    icon: "fas fa-cloud"
    items:
```
