### ISSUE TITLE
Multiple messages?

### ISSUE THREAD

**Issue by DigitalFriends** [bastienwirtz/homer#70]
Is there any way to create multiple message-boxes? I cant figure it out.

**Comment by JamiePhonic** [comment]
It doesn't look possible to enable multiple, seperate messages with config.yml

You CAN however, change the "content" of the message to include HTML tags to give you multiple lines instead.

```yaml
message:
  style: "is-warning"
  title: "Message"
  content: |
    This is one line </br>
    This is another! </br>
    <b>And this ones bold!</b>
```
In YAML, the | character after a tag tells it that everything indented below said tag should be read as one coninuous block of text, instead of more tags

**Comment by bastienwirtz** [comment]
Hi there!

It's not possible for now, but as said by @JamiePhonic, you can leverage the HTML feature to add multiple message. You can event hide the main title (`title: ~`) bar and create your own: 

```yaml
message:
  title: ~
  content: "<h1>Message 1</h1><p>...</p><h1>Message 2</h1><p>...</p>"
```

If you want the same look & style, you can use the html markup here: https://bulma.io/documentation/components/message/.
