### ISSUE TITLE
v23.09.1 container ARMv7 exits with 139

### ISSUE THREAD

**Issue by lemisieur** [bastienwirtz/homer#702]
**Describe the bug**
With the update to the `latest` tag that was made yesterday (same issue with yesterday's release `v23.09.1`), it seems like the container can't start on a ARMv7 architecture anymore. It simply exits with error code 139 after a few secs without any logs.

**Expected behavior**
A clear and concise description of what you expected to happen. v23.05.1 works fine and as expected

**Logs & errors**
No logs are being generated except for this container exit to 139.

**Screenshots**
N/A

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
---
title: "Dashboard"
subtitle: "lab.lemisieur.com"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

message:
  icon: "fa-brands fa-google"
  content: '<form action="https://google.ca/search" method="get"><input type="text" name="q" style="width: 100%;height:100%;font-weight: 400" spellcheck="false" autofocus="true" onkeydown="handleKeyPress(event)"/></form>'

services:
  - name: "//home"
    icon: "fa-solid fa-house-signal"
    items:
      - name: "homebridge"
        logo: "assets/tools/homebridge.png"
        subtitle: "XXX"
        url: "XXX"
        type: Ping
        target: "_blank"
      - name: "homeassistant"
        logo: "assets/tools/homeassistant.png"
        subtitle: "XXXX"
        url: "XXXX"
        target: "_blank"
      - name: "homebridge-cashew"
        logo: "assets/tools/homebridge.png"
        subtitle: "XXX"
        url: "XXX"
        type: Ping
        target: "_blank"

  - name: "//network"
    icon: "fa-solid fa-globe"
    items:
      - name: "dns-01"
        logo: "assets/tools/adguard.png"
        subtitle: "XXX"
        url: "XXX"
        type: Ping
        target: "_blank"
      - name: "dns-02"
        logo: "assets/tools/adguard.png"
        subtitle: "XXX"
        url: "XXXX"
        type: Ping
        target: "_blank"
      - name: "nextdns"
        logo: "assets/tools/nextdns.png"
        subtitle: "my.nextdns.io"
        url: "https://my.nextdns.io"
        type: Ping
        target: "_blank"

  - name: "//management"
    icon: "fa-solid fa-server"
    items:
      - name: proxmox
        logo: "assets/tools/proxmox.png"
        subtitle: "XXXX"
        url: XXXX
        type: Proxmox
        node: "proxmox"
        warning_value: 50
        danger_value: 80
        api_token: "XXXX"
        hide_decimals: true # removes decimals from stats values.
        hide: [] # hides information. Possible values are "vms", "vms_total", "lxcs", "lxcs_total", "disk", "mem" and "cpu".
        small_font_on_small_screens: true # uses small font on small screens (like mobile)
        small_font_on_desktop: true # uses small font on desktops (just in case you're showing much info)
      - name: portainer
        logo: "assets/tools/portainer.png"
        subtitle: "XXXX"
        url: XXXX
        type: Portainer
        apikey: XXXX
        environments:
          - rocket
      - name: proxy
        logo: "assets/tools/proxy.png"
        subtitle: "XXXX"
        url: "XXX"
        type: Ping
        target: "_blank"
      - name: nas
        logo: "assets/tools/nas.png"
        subtitle: "XXXX"
        url: "XXXX"
        target: "_blank"
      - name: printer
        logo: "assets/tools/printer.png"
        subtitle: "XXXX"
        url: "XXXX"
        target: "_blank"
      - name: certificates
        logo: "assets/tools/printer.png"
        subtitle: app.bounca.org
        url: https://app.bounca.org/auth/login
        target: "_blank"
```
