### ISSUE TITLE
Feature Request  - Don't Repeat Yourself

### ISSUE THREAD

**Issue by sohnemann** [bastienwirtz/homer#72]
As I'm hosting most of my applications on the same host, I would like to add the hostname
everywhere without repeating myself.

I basically got the basics working with YAML anchors:

```
hostname: &hostname
  url: "http://192.168.1.1"

services:
  - name: "Supervision"
    icon: "fa fa-binoculars"
    items:
      - name: "Portainer"
        logo: "/assets/tools/portainer.png"
        subtitle: "Docker management dashboard"
        >>: * hostname
```
That pretty much copies my hostname to every url.
Now my problem is that I can't seem to concatenate hostname & port or extend the url.

So what I was thinking is, that it might be possible to create nodes like in the following example:

```
hostname: &hostname
  base_url: "http://192.168.1.1"

services:
  - name: "Supervision"
    icon: "fa fa-binoculars"
    items:
      - name: "Portainer"
        logo: "/assets/tools/portainer.png"
        subtitle: "Docker management dashboard"
        >>: * hostname
        extended_url: "/portainer"
```
Then they would be concatenated for more universal usage.

If someone wouldn't want to use this feature they wouldn't have to, as base_url could still be
used like it is now with url. It's just an idea and maybe it would be possible to keep the name of the node 'url' so as not to break existing configurations.

Cheers
sohnemann
