### ISSUE TITLE
png Logo not showing

### ISSUE THREAD

**Issue by tristangrichard** [bastienwirtz/homer#731]
**Describe the bug**
I have configured a few items but none of the logos are showing beside AdGuard

**Expected behavior**
Logo are showing

**Screenshots**
<img width="984" alt="Screenshot 2024-01-05 at 19 01 56" src="https://github.com/bastienwirtz/homer/assets/13846439/86f710d4-70a6-436e-b9ed-d4f6245b8ead">
<img width="906" alt="Screenshot 2024-01-05 at 19 05 44" src="https://github.com/bastienwirtz/homer/assets/13846439/f22cf082-4d29-4db1-a7ce-64fb712a8124">

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
services:
  - name: "Servers"
    icon: "fa-solid fa-server"
    items:
      - name: "Proxmox"
        logo: "assets/tools/proxmox.png"
        subtitle: "VM"
        url: "https://192.168.1.32:8006"
      - name: "Home Assistant"
        logo: "assets/tools/ha.png"
        subtitle: "Home automation"
        tag: "app"
        url: "http://homeassistant.local:8123"
        target: "_blank" # optional html a tag target attribute
      - name: "Scrypted"
        logo: "assets/tools/scrypted.png"
        subtitle: "Homekit bridge"
        url: "https://192.168.1.35:10443"
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media server"
        tag: ""
        url: "https://192.168.1.36:32400/web"
      - name: "DSM"
        logo: "assets/tools/dsm.png"
        subtitle: "NAS"
        tag: ""
        url: "https://192.168.1.30"
      - name: "Photos"
        subtitle: "Photo album"
        logo: "assets/tools/photos.png"
        tag: ""
        url: "https://192.168.1.30/photos"
  - name: "Network"
    icon: "fa-solid fa-network-wired"
    items:
      - name: "AdGuard"
        logo: "assets/tools/adguard.png"
        subtitle: "Ad blocker"
        url: "http://192.168.1.33"
      - name: "Unifi"
        subtitle: "Network Controller"
        logo: "assets/tools/unifi.png"
        url: "https://192.168.1.1/network"
      - name: "Protect"
        subtitle: "Surveillance"
        logo: "assets/tools/protect.png"
        url: "https://192.168.1.1/protect"
```
