### ISSUE TITLE
Add ability to route relative to the current URL / browser location API

### ISSUE THREAD

**Issue by daniel-simpson** [bastienwirtz/homer#746]
**Is your feature request related to a problem? Please describe.**
I serve homer dashboard on my home server.  I usually open it by IP address (e.g. `192.168.1.119`), but if I'm outside my network I use tailscale and it's resolution to grab my dashboard (e.g. `http://nuc/`).

I host multiple other services on this machine on different ports, and would like a way to have homer resolve links relative to my current URL (either `http://192.168.1.119` or `http://nuc`).

**Describe the solution you'd like**
A concise template for generic services that allows some or all of the url property to be parameterised, e.g.:

```yaml
- name: "Relative URL example"
  icon: fa-explosion
  subtitle: A link hosted on the same server as Homer, but with more than one possible hostname
  url: "//${hostname}:8080
```

**Describe alternatives you've considered**
PR incoming, happy to make adjustments or discuss further.

**Additional context**
N/A

**Comment by zsimple** [comment]
To be honest, I'm quite surprised that Homer has developed to this current level, yet it still lacks this functionality...

I need this feature too, currently I use
```yaml
- name: "Some App"
  url: "javascript:open(`//${location.hostname}:9090/`);"
  #target: "_blank" # target must not used here
```
to do it, it works but not beatiful, hope this feature can be used soon.

**Comment by dacagi** [comment]
> To be honest, I'm quite surprised that Homer has already developed to this level, yet still lacks this functionality.
> 
> I need this feature too, beside using home DNS, currently I use blow code to get it work.
> 
> ```yaml
> - name: "Some App"
>   url: "javascript:open(`//${location.hostname}:9090/`);"
>   #target: "_blank" # target must not used here
> ```
> 
> This works, but it's rather inelegant, hope this feature can be used soon.

This solution didn't quite work for me when used inside the links list instead of the services. Or maybe it's Firefox idk. It loads the new url but on another page, and the current page shows an empty screen except the text "[object Window]".

I managed to find this though which does work, reloading the url on the current page.
```
links:
  - name: "TS"
    icon: "fas fa-table-cells"
    url: "javascript:window.location.port=8081"
```

I'm also working in a solution to allow me to have separate addresses, tailscale, lan and domain name too. So far I'm using 3 separate instances with the same configs but replacing URLs. But this, together with additional pages, should allow to have like 3 equal tabs just pointing to different ports/urls.

Thanks for the great idea!!

**Comment by zsimple** [comment]
Oh sorry, I've been using Chrome without any issues, and I haven't tested it in all browsers. It seems to be some problems in Firefox. 

Your approach is also really good, it replace the current url. But if someone still wants to open the service in a new tab, try the following method:

```yml
links:
  - name: "TS"
    icon: "fas fa-table-cells"
    url: "javascript:void(window.open(`//${location.hostname}:8081/`))"
```

It seem works well in both Chrome and Firefox, hope it can help someone.
