### ISSUE TITLE
Recomendation: Homer in combination with "Custom New Tab Page" firefox addon

### ISSUE THREAD

**Issue by vosdev** [bastienwirtz/homer#75]
After searching for some time I have come across an extension that allows me to use homer in my new tab page, without putting the homer address in my addressbar.

![image](https://user-images.githubusercontent.com/45820840/83861824-621c4280-a721-11ea-9228-41dfa37b81e2.png)

https://addons.mozilla.org/firefox/addon/custom-new-tab-page

The extension loads Homer in an iframe on your new tab page, meaning you have to add `target: '_top'` to each of your items.

This extension allows you to have your homer dashboard in your new tab page, while leaving focus on the address bar meaning you can still type right away if you want to search or go to a page that is not on your homer dash.

```yaml
- name: "Reddit"
  logo: "assets/daily/reddit.png"
  url: "https://reddit.com"
  target: '_top'

- name: "YouTube"
  logo: "assets/daily/youtube.png"
  url: "https://youtube.com"
  target: '_top'
```

This extension was the finishing touch to how I wanted to use Homer and I am so happy that I wanted to share it with other people using it. Perhaps recommend it in the README.md ?
