### ISSUE TITLE
Undocumented Feature: YAML Anchoring

### ISSUE THREAD

**Issue by JamiePhonic** [bastienwirtz/homer#76]
Not an issue, but maybe something that should be mentioned in the documentation?

I figured out that YAML Anchoring works in config.yml

For example, you can define tags and tag styles for each "item" in a service. 
Using Anchoring, you can define all your tags and their styles once like this: (for example)
```yaml
# Some pre-defined tag styles. reference these using <<: *{NAME} inside an item definition; For Example, <<: *Apps
tags: 
  Favourite: &Favourite
    - tag: "Favourite"
      tagstyle: "is-medium is-primary"
  CI: &CI
    - tag: "CI"
      tagstyle: "is-medium is-success"
  App: &App
    - tag: "App"
      tagstyle: "is-medium is-info"
```
and then simply reference these pre-defined tags in each item like so:
````yaml
- name: "VS Code"
  logo: "/assets/vscode.png"
  subtitle: "Develope Code Anywhere, On Anything!"
  <<: *App # Regerence to the predefined "App" Tag
  url: "https://vscode.example.com/"
  target: "_blank" # optional html tag target attribute
````
then, if you want to update the name or style of any perticular tag, just update it once, in the tags section! 
Great if you have a lot of services or a lot of tags!
