### ISSUE TITLE
How to fix ping CORS issue with Docker?

### ISSUE THREAD

**Issue by Tama47** [bastienwirtz/homer#775]
Referring to this:
https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md#my-custom-service-card-doesnt-work-nothing-appears-or-offline-status-is-displayed-pi-hole-sonarr-ping-

> Modify the target server configuration so that the response of the server included following header- Access-Control-Allow-Origin: * (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). It might be an option in the targeted service, otherwise depending on how the service is hosted, the proxy or web server can seamlessly add it.

> Use a cors proxy server like [cors-container](https://github.com/imjacobclark/cors-container), [cors-anywhere](https://github.com/Rob--W/cors-anywhere) or many others.

Specifically would like to do option 2 or 3, as option 1 isn't feasible.

docker-compose:
```
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: Homer
    volumes:
      - ./assets:/www/assets
    environment:
      - INIT_ASSETS=1
```

config.yaml:
```
- name: "Pi-hole - Synology"
        logo: "assets/tools/Pi-hole.svg"
        subtitle: "192.168.1.10:8080"
        url: "http://pi.hole:80"
        target: "_blank"
        tag: "Tools"
        type: Ping
```
