### ISSUE TITLE
Unable to set color of tag with Bluma class

### ISSUE THREAD

**Issue by cyrilschreiber3** [bastienwirtz/homer#792]
**Describe the bug**
I don't know if it was intentional, but [these lines](https://github.com/bastienwirtz/homer/blob/359f1ffb53cdb3476acbfcb8c1af70dff2eaf403/src/assets/components/base.scss#L184-L185) or [these lines](https://github.com/bastienwirtz/homer/blob/359f1ffb53cdb3476acbfcb8c1af70dff2eaf403/src/assets/components/base.scss#L292-L293) in your recent commit are removing the ability to change the color of each tag with a Bluma class name like `is-link`, `is-success`, etc. in the property `tagstyle` of an item.

**Expected behavior**
The color of the tag follows the Bluma class set in the `tagstyle` property.

What I suggest is that when the property is not set, the color from `highlight-secondary` is used, but when it is set, it uses the one from `tagstyle`.

**Configuration**
```yml
  - name: "Grafana"
    subtitle: "grafana.schreibernet.dev"
    logo: "./assets/icons/png/grafana.png"
    tag: "Local"
    tagstyle: "is-link" #this property is "overwritten" by the `highlight-secondary` property
    url: "https://grafana.schreibernet.dev/"
    target: "_blank"
```
