### ISSUE TITLE
[configuration question] How to remove the grouping entry?

### ISSUE THREAD

**Issue by wsw70** [bastienwirtz/homer#797]
_(apologies for posting a question here but Discussions are not enabled in the repo)_

First of all, thank you for Homer. I just installed it and it looks like this is the simple, easily configurable dashboard I've been looking for.

I want to have a plain list of services (just a set of badges with the services, no groups). Is there a way to remove the grouping entry/text that takes (in my case) some valuable space?

![image](https://github.com/user-attachments/assets/0581429a-3ac3-4a42-a6e0-466eeee299eb)

**Comment by MD023** [comment]
Hi @wsw70!

I just tested it to make sure it works, but in your config.yml file (or whatever .yml file you are using for your page), you can remove the `name` and `icon` elements of a group and just leave the cards. See below:

**Before:**
```yaml
services:
  - name: "Applications" # REMOVE THIS LINE
    icon: "fas fa-cloud" # REMOVE THIS LINE
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
```

**After:**
```yaml
services:
  - items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
```

That should do the trick :)
