### ISSUE TITLE
[Q] can I mix items  and groups?

### ISSUE THREAD

**Issue by wsw70** [bastienwirtz/homer#799]
- The default (example) configuration of Homer shows a dashboard with groups and items with the groups.
- The configuration file mentions that a "group-less" view can also be used: all items are aligned one after the other.

Is there a middle ground: the ability to use both groups and standalone items?

**Comment by MD023** [comment]
Hi again @wsw70!

If I'm understanding what you mean correctly, than yes it is technically possible to mix groups and standalone items, however there are some downsides.

## Example
![image](https://github.com/user-attachments/assets/c7ee4319-77c3-4de3-8f2c-02f5648300f7)

### config.yml
```yaml
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
        type: "SecondaryLink"
        SecondaryLinkUrl: "https://google.ca"
        SecondaryLinkTarget: "_blank"
        SecondaryLinkIcon: "fa-solid fa-circle-info fa-xl" 
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"


  - name: " "
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
        type: "SecondaryLink"
        SecondaryLinkUrl: "https://google.ca"
        SecondaryLinkTarget: "_blank"
        SecondaryLinkIcon: "fa-solid fa-circle-info fa-xl" 
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"

  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
        type: "SecondaryLink"
        SecondaryLinkUrl: "https://google.ca"
        SecondaryLinkTarget: "_blank"
        SecondaryLinkIcon: "fa-solid fa-circle-info fa-xl" 
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
```

As you can see you can mix the use of both groups and standalone items, but due to the missing header and logo, the spacing is off. To counter this slightly, and to still allow for both column and list views, you can add `- name: " "`  (just a space between the quotation marks) to the standalone "group".

This allows Homer to recognize the list of items as a group but without the header and logo. This maintains the ability to use the list and column view, but only marginally lowers the positioning so it does still appear differently than a group with a header and logo.

You may have to mess around with the ordering of the items to cater it to whatever your needs are, but this is what I was able to test. If I come across a better solution I will be sure to let you know!
