### ISSUE TITLE
custom.css not rendered

### ISSUE THREAD

**Issue by duchenpaul** [bastienwirtz/homer#814]
**Describe the bug**
I encountered exactly the same issue as #565, version is `v24.10.1`, and it was good when using `v24.05.1`.
Could be related to PR [feat(ui): Rework theming system, add new theme](https://github.com/bastienwirtz/homer/pull/789)

**Expected behavior**
I am using [Dracula Theme for Homer](https://draculatheme.com/homer), it should show the dracula theme, but it shows the default one.

**Logs & errors**
I dont see any errors in chrome console

**Screenshots**

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
# Homepage configuration
# See https://fontawesome.com/icons for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "App dashboard"
subtitle: "Homer"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "assets/images/logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false
# whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
# You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
stylesheet:
  - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
# colors:
#   light:
#     highlight-primary: "#3367d6"
#     highlight-secondary: "#4285f4"
#     highlight-hover: "#5a95f5"
#     background: "#f5f5f5"
#     card-background: "#ffffff"
#     text: "#363636"
#     text-header: "#424242"
#     text-title: "#303030"
#     text-subtitle: "#424242"
#     card-shadow: rgba(0, 0, 0, 0.1)
#     link-hover: "#363636"
#     background-image: "assets/your/light/bg.png"
#   dark:
#     highlight-primary: "#3367d6"
#     highlight-secondary: "#4285f4"
#     highlight-hover: "#5a95f5"
#     background: "#131313"
#     card-background: "#2b2b2b"
#     text: "#eaeaea"
#     text-header: "#ffffff"
#     text-title: "#fafafa"
#     text-subtitle: "#f5f5f5"
#     card-shadow: rgba(0, 0, 0, 0.4)
#     link-hover: "#ffdd57"
#     background-image: "assets/your/dark/bg.png"

# Optional message
# message:
#   # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
#   style: "is-warning"
#   title: "Optional message!"
#   icon: "fa fa-exclamation-triangle"
#   content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
...
```

assets dir:
```
/www/assets $ ll
total 384
drwxr-xr-x    4 root     root          4096 Oct 22 13:54 .
drwxr-xr-x    1 root     root          4096 May 22 07:30 ..
-rwxrwxr-x    1 root     root          8461 Oct 22 13:53 config.yml
-rw-r--r--    1 root     root          4024 Oct 22 13:54 custom.css
-rwxrwxr-x    1 root     root          4492 Oct 22 13:53 device.yml
-rw-r--r--    1 root     root        348137 Oct 22 13:54 dracula-background.png
drwxr-xr-x    2 root     root          4096 Oct 22 13:54 images
-rwxrwxr-x    1 root     root          3338 Oct 22 13:53 public.yml
drwxr-xr-x    2 root     root          4096 Oct 22 13:53 theme
```
