### ISSUE TITLE
Message not fetched when changing page with navbar

### ISSUE THREAD

**Issue by LukeFiddy** [bastienwirtz/homer#828]
**Describe the bug**
The request for the message is not sent when changing page using the navbar. upon refreshing the page the request is sent and the message is displayed. Setting the refreshInterval does not cause the request to be sent after the interval either.

**Expected behavior**
Upon changing page, the request for the message should be sent and the message should be displayed.

**Configuration**
table.yml:
```
---
message:
  url: /lb-info
  title: 'Static IP Table'
  mapping:
    content: 'table'
  content: 'Message could not be loaded, try refreshing'
```

config.yml excerpt:
```
links:
  - name: "Home"
    icon: 
    url: "#" 

  - name: "Static IP table"
    icon: 
    url: "#table" 


```
