### ISSUE TITLE
[feature request] Multiple URLs per item

### ISSUE THREAD

**Issue by rmoriz** [bastienwirtz/homer#840]
Hi,

let's say one has a service group item named "Router". Imagine the router has several URLs that one frequently wants to access, like:

```
- https://router.local/system/logs 
- https://router.local/system/dhcp/1/leases#IPv4
- https://router.local/system/traffic/by-device/eth6#ipv6-vlan666
```

As far as I know, it's currently only possible to specify one URL per item/card.
Creating an YAML item for each URL would quickly fill the page and lower the information density.

I suggest something like:

```YAML
services:
  - name: Infrastructure
    icon: "fas fa-server"
    items:
      - name: "Router"
        icon: "fa-solid fa-network-wired"
        subtitle: "the main one"
        tag: "router"
        url:
          - "https://router.local/"
        quick:
          - name: "Logs"
            url: "https://router.local/system/logs"
          - name: "DHCP IPv4 leases"
            url: "https://router.local/system/dhcp/1/leases#IPv4"
          - name: "Traffic on IPv6 lab interface"
            url: "https://router.local/system/traffic/by-device/eth6#ipv6-vlan666"
```

The links should be displayed as a list inside the main item-card below the subtitle.

What do you think?
