### ISSUE TITLE
Immich stats load error

### ISSUE THREAD

**Issue by lgwapnitsky** [bastienwirtz/homer#842]
Immich stats are not loading - receiving a 401 on valid API k ey

**Expected behavior**
Immich smart card should load status

**Logs & errors**
```
  GET https://photos.domain.com/api/server/statistics 401 (Unauthorized)
fetch @ service-CvN87575.js:1
```

**Screenshots**
![2024-12-13_09-09](https://github.com/user-attachments/assets/e3fd5406-eee1-4e14-a5a2-738e7f1e01ad)

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
      - name: Photos (Immich)
        type: Immich
        url: https://photos.domain.com
        logo: assets/tools/immich.png
        apiKey: y******************************4
        updateInterval: 5000
        target: _blank

```
