### ISSUE TITLE
Quick icon does not appear unless the parent service item also has an icon

### ISSUE THREAD

**Issue by tanasegabriel** [bastienwirtz/homer#874]
**Describe the bug**
The recently introduced "quick" links do not surface their icons if the parent service item has no icon.

```yaml
  - name: Dev Tools
    logo: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/terminal.webp
    items:
      - name: Grafana
        logo: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/grafana.webp
        url: https://grafana.<domain_redacted>/dashboards
        quick:
          - name: Test
            icon: fa-solid fa-chart-line
            url: https://1.1.1.1
```

![Image](https://github.com/user-attachments/assets/00232ae3-b8f8-4ca9-95fc-03c58bc91aae)

It seems there is a conditional around the `item` also having an icon (I use logos everywhere). If I simply add `icon: true` to the item:

```yaml
  - name: Dev Tools
    logo: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/terminal.webp
    items:
      - name: Grafana
        logo: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/grafana.webp
        url: https://grafana.<domain_redacted>/dashboards
        icon: true
        quick:
          - name: Test
            icon: fa-solid fa-chart-line
            url: https://1.1.1.1
```

![Image](https://github.com/user-attachments/assets/64125d85-0cf6-488e-9180-1ddf387df23d)

But as you can see, that messes with the padding in this scenario.

**Expected behavior**
Quick icons should be present regardless of the configuration of the parent item. Tangentially, it seems the `Ping` custom service clashes with quick icons, as they cannot be used in this combination, but it is understandable if this is outside the scope of this.
