### ISSUE TITLE
Disable light/dark toggle button

### ISSUE THREAD

**Issue by TDuffinNTU** [bastienwirtz/homer#876]
**Is your feature request related to a problem? Please describe.**
There isn't any way to disable the light/dark theme toggle.

**Describe the solution you'd like**
I'd like to have a single theme, instead of "light vs dark". Though this still keeps the toggle, which is now useless.

**Describe alternatives you've considered**
Right now, I've just commented out the light theme in my config.yaml

**Additional context**
A `theme-toggle` tag that can be given `false/light/dark` to disable/set a default theme could be cool?

**Comment by BeyondEvil** [comment]
Here's the workaround I deployed:

```css
.navbar-item[aria-label="Toggle dark mode"] {
        display: none;
    }
```
