### ISSUE TITLE
Container gets stuck in a loop trying to start the webserver

### ISSUE THREAD

**Issue by varosengineer** [bastienwirtz/homer#891]
**Describe the bug**
I'm trying to deploy Homer on my Raspberry Pi 2 with Docker, but after deployment, the container keeps looping trying to start the webserver.

**Expected behavior**
The container deploys correctly, the webserver starts and I can access the UI.

**Logs & errors**
```bash
No configuration found, installing default config & assets
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
Starting webserver
```
```bash
docker ps -a | grep homer
ad78da83d6e4   b4bz/homer:latest                 "/bin/sh /entrypoint…"   6 minu
tes ago   Restarting (139) 45 seconds ago

homer
```
```bash
docker inspect homer | grep -i error
            "Error": "",
```
```bash
docker run --rm -it b4bz/homer sh
No configuration found, installing default config & assets
cp: overwrite '/www/assets/additional-page.yml.dist'? cp: overwrite '/www/assets
/config-demo.yml.dist'? cp: overwrite '/www/assets/config.yml.dist'? cp: overwri
te '/www/assets/custom.css.sample'? cp: overwrite '/www/assets/icons/favicon.ico
'? cp: overwrite '/www/assets/icons/pwa-512x512.png'? cp: overwrite '/www/assets
/icons/logo.svg'? cp: overwrite '/www/assets/icons/pwa-192x192.png'? cp: overwri
te '/www/assets/icons/README.md'? cp: overwrite '/www/assets/icons/apple-touch-i
con.png'? cp: overwrite '/www/assets/manifest.json'? cp: overwrite '/www/assets/
themes/walkxcode/wallpaper-light.webp'? cp: overwrite '/www/assets/themes/walkxc
ode/wallpaper.webp'? cp: overwrite '/www/assets/tools/bmc-logo-no-background.png
'? cp: overwrite '/www/assets/tools/sample2.png'? cp: overwrite '/www/assets/too
ls/sample.png'? Starting webserver
```

**Screenshots**

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml

---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href=$
# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/$

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config val$
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not$
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Get started"
        icon: "fa-solid fa-download"
        subtitle: "Start using Homer in a few minutes"
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer?tab=readme-ov-file#get-started"
      - name: "Configuration"
        icon: "fa-solid fa-sliders"
        subtitle: "Configuration options documentation"
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"
      - name: "Theming"
        icon: "fa-solid fa-palette"
        subtitle: "Customize Homer appearance"
        tag: "theming"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/theming.md"
      - name: "Smart cards"
        icon: "fa-solid fa-palette"
        subtitle: "Displays dynamic information or actions."
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md"
      - name: "Dashboard icons"
        icon: "fa-solid fa-icons"
        subtitle: "Dashboard icons"
        tag: "setup"
        url: "https://github.com/walkxcode/dashboard-icons"
```
