### ISSUE TITLE
Linkding

### ISSUE THREAD

**Issue by DhruvaSambrani** [bastienwirtz/homer#909]
**Describe the bug**
Linkdink smart card has no logos only alt text

**Expected behavior**
linkding smart card has logos which are the website icons

**Logs & errors**
Please include any usefull information:
- Errors in your browser console (`ctrl+shift+i` or `F12`)
- If applicable, your docker container logs.

**Screenshots**

![Image](https://github.com/user-attachments/assets/83d3d55b-8968-4eaf-b6a3-96bc75506a6e)

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
      - name: "FreshRSS"
        type: "FreshRSS"
        logo: "/freshrss/themes/icons/FreshRSS-logo.svg"
        endpoint: "/freshrss"
        url: "/freshrss"
        username: "dhruva"
        password: "night1902__"
        tag: "rss"
        keywords: "self hosted rss"
        target: "_blank"
```
