### ISSUE TITLE
Plex Custom Service does not work

### ISSUE THREAD

**Issue by tarasifua** [bastienwirtz/homer#922]
**Describe the bug**
I have my Plex service configured by next way:
```yml
     - name: "Plex"
        logo: "assets/icons/Icons/plex.png"
        url: "https://plex.mydomain.com"
        token: "my-plex-token"
        type: "Plex"
        endpoint: "http://192.168.111.118:32400"
```

And Plex service does not appear at homepage at all. If I remove token, type and endpiont parameters, it appears, but without any info, as legacy service

**Expected behavior**

**Logs & errors**
Errror in browser console:
`index-DtQJUVrN.js:14 Error: Unknown variable dynamic import: ./services/Plex.vue
    at index-DtQJUVrN.js:148:17623
    at new Promise (<anonymous>)
    at Ud (index-DtQJUVrN.js:148:17529)
    at index-DtQJUVrN.js:148:17919
    at m (index-DtQJUVrN.js:14:4383)
    at setup (index-DtQJUVrN.js:14:5216)
    at Zs (index-DtQJUVrN.js:14:38)
    at Nu (index-DtQJUVrN.js:14:36469)
    at Iu (index-DtQJUVrN.js:14:36258)
    at Os (index-DtQJUVrN.js:14:21306)
Ef	@	index-DtQJUVrN.js:14`

**Screenshots**

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml

```
