### ISSUE TITLE
Incorrect Pi-Hole API url with v6 API and admin suffix

### ISSUE THREAD

**Issue by eoleedi** [bastienwirtz/homer#924]
**Describe the bug**
When the Pi-hole URL is `https://pihole.example.com/admin`(ends with admin suffix) with API version v6, the Pi-hole service will not work due to an incorrect base URL.

v5 API endpoint: `https://pihole.example.com/admin/api`
v6 API endpoint: `https://pihole.example.com/api`, but configured as `https://pihole.example.com/admin/api`

**Expected behavior**
The additional Pi-hole service should work when there is a suffix admin in the URL

**Logs & errors**
![Image](https://github.com/user-attachments/assets/b1fd1452-b92d-4aec-a96e-9c87ccc58685)

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
- name: "Pi-hole"
  url: "https://<pihole-domain>/admin"
  apikey: "<the-api-key>"
  apiVersion: 6
  type: "PiHole"
```

**Comment by eoleedi** [comment]
Ahh... I accidentally missed the documentation on the URL
https://github.com/bastienwirtz/homer/blob/1afa0afd00428f320fa8dd5108d5caee51e4f245/docs/customservices.md?plain=1#L471

**Comment by lexathon** [comment]
But if you don't include /admin in the URL it won't resolve to the pihole dashboard when you click it? Or am I missing something?

**Comment by eoleedi** [comment]
Exactly! So I figured out a way to use the endpoint variable as stated in the PR.

**Comment by Tooa** [comment]
Hi 👋 ,
this issue got my attention while reading the latest release notes. 

The new Pi-hole V6 release can automatically redirect to `/admin` if you configure `FTLCONF_webserver_domain` (docker install) to the FQDN of your running instance (e.g. `pihole.home.internal`). Then you can also remove the redirect middleware in case you run your Pi-Hole behind a reverse proxy.

This allows to solely rely on the `url` in Homer:

```yaml
      - name: "Pi-hole"
        logo: "assets/tools/pi-hole.png"
        url: "https://pihole1.home.internal"
        type: "PiHole"
        apikey: <redacted>
        apiVersion: 6
 
```

See this [Reddit Post](https://www.reddit.com/r/pihole/comments/1iu44g8/pihole_v6_traefik_fix/) for more information.
