### ISSUE TITLE
How to update docker container?

### ISSUE THREAD

**Issue by HolgerAusB** [bastienwirtz/homer#934]
I am not a docker pro. I am updating homer like I do for other docker containers and thought all works well. But now I found out, that the working container is two years old. Every time I did the pull, I got an error that port 8080 is already bound. I have done a reboot then and thought that will do the trick, but it doesn't.

How should I do the update the correct way? Please put that hint to the docs, too.

How do I get rid of that old container/image? `rm` seems not to work

My update script:

```cmd
cd /path/to/dockers/homer

echo Stop container
docker compose down
sleep 2

echo get update
docker compose pull

echo remove old container
docker compose rm

echo Start new container
docker compose up -d
```

My docker-compose.yml:

```yml
services:
  homer:
    image: b4bz/homer:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /path/to/dockers/homer/assets:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped
    dns:
      - 192.xxx.xxx.1
      - 192.xxx.xxx.2
```

Here is the output of my update script and a following `docker images`:

![Image](https://github.com/user-attachments/assets/edfb15da-139d-4b51-bf03-33f0e23c3495)

```console
xxxxx05:/path/to/dockers/homer $ docker rm ab0a43829253
Error response from daemon: No such container: ab0a43829253
```
