### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by treypop** [bastienwirtz/homer#945]
**Describe the bug**
I have set the icons for multiple services and they do not appear in the browser. 

**Expected behavior**
The icon to appear next to the name of the service.

**Screenshots**
![Image](https://github.com/user-attachments/assets/9ac3cc7e-294b-49bf-97a8-469968f4a4dd)

**Configuration**
```services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Home Assistant"
        icon: "assets/icons/home_assistant.svg"
        subtitle: "Start using Homer in a few minutes"
        tag: ""
        url: "https://homeassistant.com"
      - name: "Pi-hole"
        icon: "assets/icons/pi-hole.svg"
        subtitle: "Configuration options documentation"
        tag: ""
        url: "http://pi-hole.com"
      - name: "Theming"
        icon: "fa-solid fa-palette"
        subtitle: "Customize Homer appearance"
        tag: "theming"
        url: "https://github.com/bastienwirtz/homer/blo>
      - name: "Smart cards"
        icon: "https://cdn.jsdelivr.net/gh/homarr-labs/>
        subtitle: "Displays dynamic information or acti>
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer/blo>
      - name: "Dashboard icons"
        icon: "fa-solid fa-icons"
        subtitle: "Dashboard icons"
        tag: "setup"
        url: "https://github.com/walkxcode/dashboard-ic>

```

**Comment by thibaut1304** [comment]
Hello,

Just a quick note:
The URL you're using for the Smart cards icon (https://cdn.jsdelivr.net/gh/homarr-labs/) doesn't point to a valid image file (.svg or .png), so it's normal that the icon doesn't show up.

👉 To use a custom image (SVG or PNG), it's preferable to use the logo: property instead of icon:. That's how I did it on my setup.

And if the icon still doesn't appear even with a correct URL, make sure your Docker volume is properly mounted inside the Homer container so that the assets/ folder is accessible from within.

**Comment by treypop** [comment]
> Just a quick note: The URL you're using for the Smart cards icon (https://cdn.jsdelivr.net/gh/homarr-labs/) doesn't point to a valid image file (.svg or .png), so it's normal that the icon doesn't show up.

I fixed the URL.
> 
> 👉 To use a custom image (SVG or PNG), it's preferable to use the logo: property instead of icon:. That's how I did it on my setup.
 
What do you mean by use the logo?
> And if the icon still doesn't appear even with a correct URL, make sure your Docker volume is properly mounted inside the Homer container so that the assets/ folder is accessible from within.

I am not using docker to run homer

**Comment by MinecraftDocker** [comment]
@thibaut1304 

I am getting the same exact issue. I am running Homer in Docker Compose, with `homer-config` passed through in the compose file. The `homer-icons` folder is located in `homer-config/icons/homer-icons`. I previously had created an `assets` folder under `homer-config`, but experienced the same issue.
When using the `icon:` method, there is no icon present, like OP. If I use the `logo:` method, I get this little "img not found icon", _even when using fas icons._

![Image](https://github.com/user-attachments/assets/6d7f7d25-401c-4192-8e86-cfabff56b10c)

If I use a url like this (https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg), the `logo:` method works, but the `icon:` doesn't.
So to clarify:
- `icon:` Works with `fas` icons, but local and url files are blank.
- `logo:` Shows "img not found" icon with local and `fas` icons, but works with urls.

Any thoughts?

**Comment by thibaut1304** [comment]
@treypop 


In this example, there are two issues: using the `icon` key instead of `logo`.
Then there's an error with the path to the png or svg file!
```yaml
services:
  - name: "Admin"
    icon: "fas fa-cogs"
    items:
      - name: "Wireguard"
        icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wireguard-transparent.svg"
        url: "https://vpn.thibaut-husser.com"
        type: Wg-easy
        basic_auth: "secret://basic_auth"
      - name: "Wireguard"
        logo: "assets/icons/wireguar-transparent.png"
        url: "https://vpn.thibaut-husser.com"
        type: Wg-easy
        basic_auth: "secret://basic_auth"
      - name: "Wireguard"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wireguard-transparent.svg"
        url: "https://vpn.thibaut-husser.com"
        type: Wg-easy
        basic_auth: "secret://basic_auth"
```

![Image](https://github.com/user-attachments/assets/1ae699c7-2c68-44c5-adb1-fbde038d40ea)
